In [1]:
%pip install xgboost imbalanced-learn scikit-learn pandas numpy matplotlib seaborn joblib lightgbm optuna

Requirement already satisfied: xgboost in ./.venv/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: imbalanced-learn in ./.venv/lib/python3.14/site-packages (0.14.1)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.6)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.10.9)
Requirement already satisfied: seaborn in ./.venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: joblib in ./.venv/lib/python3.14/site-packages (1.5.3)
Requirement already satisfied: lightgbm in ./.venv/lib/python3.14/site-packages (4.6.0)
Requirement already satisfied: optuna in ./.venv/lib/python3.14/site-packages (4.8.0)
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in ./.venv/lib/python3.14/site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in ./.venv/lib/python3.14/site-packages (from imbalanced-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: alembic>=1.5.0 in ./.venv/lib/python3.14/site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in ./.venv/lib/python3.14/site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in ./.venv/lib/python3.14/site-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in ./.venv/lib/python3.14/site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.14/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in ./.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in ./.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.venv/lib/python3.14/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

### Data Preparation

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import KNNImputer, SimpleImputer
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import lightgbm as lgb
import warnings
warnings.filterwarnings('ignore')

In [3]:
hot_rolling_df = pd.read_csv('dataset/train.csv')
print(f"Hot Rolling Dataset Shape : {hot_rolling_df.shape}")
hot_rolling_df.head(20)

Hot Rolling Dataset Shape : (1352, 51)

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
0,487,854.787195,501.088868,414.841484,710.583316,662.072013,656.076977,547.040479,563.653582,495.296785,...,0.201645,0.047960,0.267467,0.052247,-0.893174,0.000000,0.028925,0.000534,0.010797,0.0
1,44,1056.526699,868.083321,622.879982,725.276469,665.235554,647.450550,552.333202,565.105074,493.310075,...,0.644403,0.000000,0.341870,0.153513,25.471899,0.002520,0.033281,0.028349,0.079602,0.0
2,192,1095.648362,668.112517,695.787904,716.773671,662.843475,657.542380,549.863867,546.210823,482.814753,...,0.486502,0.000000,0.202539,0.168192,-25.764196,0.002072,0.033878,0.000000,0.058266,0.0
3,1552,1050.943543,660.340015,440.280245,611.562496,628.081103,561.397721,456.816210,550.103433,378.353283,...,1.198010,0.020787,0.288786,0.329108,1.033840,0.000250,0.045490,0.039004,0.004850,0.0
4,1190,1091.640314,297.363775,842.665620,749.160886,652.992309,615.576656,608.364764,549.756758,487.753140,...,0.237231,0.000841,0.257281,0.112637,-11.130157,0.002376,0.031298,0.003623,0.018434,0.0
5,102,1060.742584,809.756675,675.882581,726.410383,672.159859,661.250928,555.468859,554.440758,492.462056,...,0.810914,0.043039,0.274467,0.250703,28.221606,0.002755,0.049610,0.001055,0.117253,0.0
6,900,1087.182781,513.823963,434.777529,727.732813,661.179522,606.946096,539.393969,532.864699,480.662740,...,0.565355,0.000846,0.341627,0.115135,8.942980,0.002918,0.051415,0.029154,0.084616,0.0
7,674,1082.185852,328.168651,395.732261,610.456744,650.491924,532.674335,467.587611,544.260627,486.572833,...,0.198847,0.001384,0.256416,0.042418,21.992259,0.000704,0.039402,0.000028,0.009336,0.0
8,572,1111.579895,909.156996,317.875943,731.479162,672.679098,663.639612,547.616420,571.662343,490.837575,...,0.518436,0.000000,0.215945,0.051108,-17.106723,0.000842,0.037112,0.002238,0.011166,0.0
9,1205,1037.383965,609.839905,513.596340,728.363034,645.250990,590.713451,601.842899,520.893575,484.417182,...,1.010123,0.000000,0.231285,0.010257,6.860036,0.002862,0.047626,0.032069,0.119772,0.0
10,1081,1083.697248,572.391786,671.363477,737.848661,650.785937,604.239124,546.626007,525.499437,478.915896,...,0.461687,0.001894,0.304753,0.073592,4.354575,0.001870,0.050725,0.001415,0.006052,0.0
11,314,1008.180963,709.665138,630.827271,605.168675,597.404223,546.726893,444.531271,550.249659,487.746522,...,0.879044,0.046486,0.272398,0.091139,13.197569,0.002377,0.033046,0.000545,0.145210,0.0
12,1228,1097.478596,567.979471,523.921210,623.240825,581.404728,563.013462,451.812520,540.824982,415.031696,...,0.838788,0.049190,0.221663,0.023326,3.498766,0.002354,0.042453,0.000000,0.148410,0.0
13,944,1102.735733,602.313220,520.071286,729.700843,664.951333,612.754181,558.214284,550.691257,492.340875,...,0.517536,0.002737,0.364665,0.146593,19.403038,0.001318,0.052653,0.001870,0.074739,0.0
14,516,1058.259850,203.672905,217.861576,735.985361,658.214744,655.293485,545.840209,560.555212,491.731852,...,0.610901,0.019341,0.223121,0.036305,26.023011,0.001399,0.045250,0.000000,0.003763,0.0
15,912,1078.860939,656.695718,566.652073,742.074991,660.117144,612.993051,547.970221,553.210440,474.479272,...,0.778340,0.012607,0.321385,0.136010,-0.939537,0.001794,0.050302,0.000695,0.019277,0.0
16,189,1080.264944,497.387805,635.200240,724.704393,668.621530,662.383468,550.844784,547.513319,487.717931,...,0.524678,0.000000,0.191361,0.165117,-17.519580,0.002364,0.050070,0.000000,0.053662,0.0
17,1016,1077.266535,440.590656,494.504324,735.538765,668.925677,612.806052,549.802155,544.383220,474.622249,...,0.742090,0.009886,0.184221,0.007917,-12.072707,0.000514,0.033293,0.002611,0.005861,0.0
18,1529,933.734873,801.510280,627.868619,737.419350,748.141192,712.865662,591.424888,538.684623,479.168138,...,0.519538,0.000695,0.164385,0.004205,1.666199,0.000000,0.046633,0.003317,0.067964,0.0
19,1619,1029.273576,812.375220,395.471733,610.271229,618.513558,585.045612,468.386640,460.249033,397.309193,...,1.223748,0.016347,0.217337,0.011733,4.047144,0.003039,0.049347,0.040050,0.125722,0.0

In [4]:
# Check for the missing values in the before starting to 'impute' in the  dataset
missing_values = hot_rolling_df.isnull().sum()
print("Missing values in each of the column features in the dataset : \n", missing_values)
hot_rolling_df.info()
hot_rolling_df.describe()

Missing values in each of the column features in the dataset :
 CoilID      0
X1          0
X2          0
X3          0
X4          0
X5          0
X6          0
X7          0
X8          1
X9          0
X10         6
X11         0
X12         0
X13         0
X14         0
X15       160
X16         6
X17         0
X18         0
X19         0
X20         0
X21         1
X22         0
X23         6
X24         6
X25         6
X26         7
X27         6
X28         0
X29         0
X30         0
X31         0
X32         0
X33         0
X34         0
X35         0
X36         0
X37         0
X38         0
X39         0
X40         0
X41         0
X42        31
X43         0
X44         0
X45         0
X46         0
X47         0
X48        13
X49         0
Y           0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 51 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CoilID  1352 non-null   int64
 1   X1      1352 non-null   float64
 2   X2      1352 non-null   float64
 3   X3      1352 non-null   float64
 4   X4      1352 non-null   float64
 5   X5      1352 non-null   float64
 6   X6      1352 non-null   float64
 7   X7      1352 non-null   float64
 8   X8      1351 non-null   float64
 9   X9      1352 non-null   float64
 10  X10     1346 non-null   float64
 11  X11     1352 non-null   float64
 12  X12     1352 non-null   float64
 13  X13     1352 non-null   float64
 14  X14     1352 non-null   float64
 15  X15     1192 non-null   float64
 16  X16     1346 non-null   float64
 17  X17     1352 non-null   float64
 18  X18     1352 non-null   float64
 19  X19     1352 non-null   float64
 20  X20     1352 non-null   float64
 21  X21     1351 non-null   float64
 22  X22     1352 non-null   float64
 23  X23     1346 non-null   float64
 24  X24     1346 non-null   float64
 25  X25     1346 non-null   float64
 26  X26     1345 non-null   float64
 27  X27     1346 non-null   float64
 28  X28     1352 non-null   float64
 29  X29     1352 non-null   float64
 30  X30     1352 non-null   float64
 31  X31     1352 non-null   float64
 32  X32     1352 non-null   float64
 33  X33     1352 non-null   float64
 34  X34     1352 non-null   float64
 35  X35     1352 non-null   float64
 36  X36     1352 non-null   float64
 37  X37     1352 non-null   float64
 38  X38     1352 non-null   float64
 39  X39     1352 non-null   float64
 40  X40     1352 non-null   float64
 41  X41     1352 non-null   float64
 42  X42     1321 non-null   float64
 43  X43     1352 non-null   float64
 44  X44     1352 non-null   float64
 45  X45     1352 non-null   float64
 46  X46     1352 non-null   float64
 47  X47     1352 non-null   float64
 48  X48     1339 non-null   float64
 49  X49     1352 non-null   float64
 50  Y       1352 non-null   float64
dtypes: float64(50), int64(1)
memory usage: 538.8 KB

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1351.000000,1352.000000,...,1352.000000,1321.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1339.000000,1352.000000,1352.000000
mean,833.515533,1028.915322,575.374555,538.372787,692.576938,649.010832,618.584573,529.241056,528.770054,461.699867,...,0.585886,0.011334,0.281290,0.091495,11.507361,0.002745,0.050913,0.007108,0.064400,0.048817
std,487.420566,108.505011,232.103882,135.288085,56.798904,35.398207,45.602831,46.263179,40.220201,40.600916,...,0.296115,0.017114,0.068455,0.073058,25.004864,0.006660,0.044617,0.012504,0.050905,0.215564
min,1.000000,235.252250,96.755492,124.150450,575.916250,559.272859,529.937396,439.221384,425.413251,343.110465,...,0.077352,0.000000,0.029599,0.000000,-82.672877,0.000000,0.016833,0.000000,0.000000,0.000000
25%,411.250000,1009.279089,405.533242,441.585514,622.213663,625.327743,583.363796,476.813303,520.192858,423.604248,...,0.365881,0.000380,0.244377,0.026073,-1.368777,0.000943,0.039864,0.000000,0.015624,0.000000
50%,824.500000,1071.978233,589.160841,548.035306,724.970407,661.170690,615.240491,547.648095,545.399528,482.412285,...,0.574328,0.002613,0.293164,0.076108,9.177752,0.001644,0.045829,0.001056,0.060336,0.000000
75%,1254.250000,1092.031100,725.766924,632.238363,734.453213,668.054192,659.564239,554.584166,556.334294,488.713960,...,0.797025,0.013933,0.334613,0.143156,24.196605,0.002275,0.051435,0.002679,0.106017,0.000000
max,1691.000000,1124.903234,1148.171484,1026.915778,755.983296,763.257466,742.725523,618.947910,575.312130,505.349388,...,1.377925,0.062637,0.409739,0.329108,120.169658,0.064545,0.424405,0.051150,0.249522,1.000000

In [5]:
# Separating the features and the target variable 'Y'

X_hot_rolling = hot_rolling_df.drop(columns=['CoilID', 'Y'])
Y_hot_rolling = hot_rolling_df['Y']

In [6]:
# Handling the missing values using the Imputer (KNNImputer)

imputer = KNNImputer(n_neighbors=5)
X_hot_rolling_imputed = imputer.fit_transform(X_hot_rolling)
# converting it to the dataframe
X_hot_rolling_imputed = pd.DataFrame(X_hot_rolling_imputed, columns=X_hot_rolling.columns)


# checking the missing values after imputation
print("Missing values after imputation: ")
print(X_hot_rolling_imputed.isnull().sum())
print("Shape of the imputed dataset: ", X_hot_rolling_imputed.shape)

hot_rolling_df.info()
hot_rolling_df.describe()

Missing values after imputation:
X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
X24    0
X25    0
X26    0
X27    0
X28    0
X29    0
X30    0
X31    0
X32    0
X33    0
X34    0
X35    0
X36    0
X37    0
X38    0
X39    0
X40    0
X41    0
X42    0
X43    0
X44    0
X45    0
X46    0
X47    0
X48    0
X49    0
dtype: int64
Shape of the imputed dataset:  (1352, 49)
<class 'pandas.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 51 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CoilID  1352 non-null   int64
 1   X1      1352 non-null   float64
 2   X2      1352 non-null   float64
 3   X3      1352 non-null   float64
 4   X4      1352 non-null   float64
 5   X5      1352 non-null   float64
 6   X6      1352 non-null   float64
 7   X7      1352 non-null   float64
 8   X8      1351 non-null   float64
 9   X9      1352 non-null   float64
 10  X10     1346 non-null   float64
 11  X11     1352 non-null   float64
 12  X12     1352 non-null   float64
 13  X13     1352 non-null   float64
 14  X14     1352 non-null   float64
 15  X15     1192 non-null   float64
 16  X16     1346 non-null   float64
 17  X17     1352 non-null   float64
 18  X18     1352 non-null   float64
 19  X19     1352 non-null   float64
 20  X20     1352 non-null   float64
 21  X21     1351 non-null   float64
 22  X22     1352 non-null   float64
 23  X23     1346 non-null   float64
 24  X24     1346 non-null   float64
 25  X25     1346 non-null   float64
 26  X26     1345 non-null   float64
 27  X27     1346 non-null   float64
 28  X28     1352 non-null   float64
 29  X29     1352 non-null   float64
 30  X30     1352 non-null   float64
 31  X31     1352 non-null   float64
 32  X32     1352 non-null   float64
 33  X33     1352 non-null   float64
 34  X34     1352 non-null   float64
 35  X35     1352 non-null   float64
 36  X36     1352 non-null   float64
 37  X37     1352 non-null   float64
 38  X38     1352 non-null   float64
 39  X39     1352 non-null   float64
 40  X40     1352 non-null   float64
 41  X41     1352 non-null   float64
 42  X42     1321 non-null   float64
 43  X43     1352 non-null   float64
 44  X44     1352 non-null   float64
 45  X45     1352 non-null   float64
 46  X46     1352 non-null   float64
 47  X47     1352 non-null   float64
 48  X48     1339 non-null   float64
 49  X49     1352 non-null   float64
 50  Y       1352 non-null   float64
dtypes: float64(50), int64(1)
memory usage: 538.8 KB

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1351.000000,1352.000000,...,1352.000000,1321.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1339.000000,1352.000000,1352.000000
mean,833.515533,1028.915322,575.374555,538.372787,692.576938,649.010832,618.584573,529.241056,528.770054,461.699867,...,0.585886,0.011334,0.281290,0.091495,11.507361,0.002745,0.050913,0.007108,0.064400,0.048817
std,487.420566,108.505011,232.103882,135.288085,56.798904,35.398207,45.602831,46.263179,40.220201,40.600916,...,0.296115,0.017114,0.068455,0.073058,25.004864,0.006660,0.044617,0.012504,0.050905,0.215564
min,1.000000,235.252250,96.755492,124.150450,575.916250,559.272859,529.937396,439.221384,425.413251,343.110465,...,0.077352,0.000000,0.029599,0.000000,-82.672877,0.000000,0.016833,0.000000,0.000000,0.000000
25%,411.250000,1009.279089,405.533242,441.585514,622.213663,625.327743,583.363796,476.813303,520.192858,423.604248,...,0.365881,0.000380,0.244377,0.026073,-1.368777,0.000943,0.039864,0.000000,0.015624,0.000000
50%,824.500000,1071.978233,589.160841,548.035306,724.970407,661.170690,615.240491,547.648095,545.399528,482.412285,...,0.574328,0.002613,0.293164,0.076108,9.177752,0.001644,0.045829,0.001056,0.060336,0.000000
75%,1254.250000,1092.031100,725.766924,632.238363,734.453213,668.054192,659.564239,554.584166,556.334294,488.713960,...,0.797025,0.013933,0.334613,0.143156,24.196605,0.002275,0.051435,0.002679,0.106017,0.000000
max,1691.000000,1124.903234,1148.171484,1026.915778,755.983296,763.257466,742.725523,618.947910,575.312130,505.349388,...,1.377925,0.062637,0.409739,0.329108,120.169658,0.064545,0.424405,0.051150,0.249522,1.000000

In [7]:
# Feature Scaling or Normalization of the dataset

scaler = StandardScaler()
X_hot_rolling_scaled = scaler.fit_transform(X_hot_rolling_imputed)

In [8]:
# Feature Scaling 

from sklearn.feature_selection import SelectFromModel, mutual_info_classif

mi_scores_hot_rolling = mutual_info_classif(X_hot_rolling_scaled, Y_hot_rolling, random_state=42)
mi_series_hot_rolling = pd.Series(mi_scores_hot_rolling, index=X_hot_rolling.columns).sort_values(ascending=False)

print("Top 10 features based on the Mutual Information Scores: \n", mi_series_hot_rolling.head(10))

Top 10 features based on the Mutual Information Scores:
 X36    0.039463
X13    0.038971
X34    0.033676
X32    0.033534
X39    0.030829
X10    0.028052
X30    0.027061
X6     0.026641
X35    0.026247
X33    0.024256
dtype: float64

In [9]:
# Selecting the top 20 features 

top_20_features_hot_rolling = mi_series_hot_rolling.head(20).index.tolist()

X_hot_rolling_selected = X_hot_rolling_imputed[top_20_features_hot_rolling]

print("shape of the dataset after the feature selection: ", X_hot_rolling_selected.shape)

X_hot_rolling_selected.describe()

shape of the dataset after the feature selection:  (1352, 20)

,X36,X13,X34,X32,X39,X10,X30,X6,X35,X33,X31,X28,X18,X15,X38,X29,X37,X5,X41,X24
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1.352000e+03,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000
mean,2279.289201,868.915869,2359.427515,15.998457,162.281065,6.861327,10.095567,618.584573,9.922451e+06,17.119898,13.506972,4.749715,890.539824,3.446813,690.497041,6.948415,1641.233728,649.010832,0.585886,16.349268
std,1767.389750,397.296095,1770.224468,3.784762,11.368766,2.631377,2.250786,45.602831,6.665497e+06,3.670994,3.259872,0.602077,7.991223,2.172425,1263.545639,1.093988,1741.161108,35.398207,0.296115,4.990185
min,0.000000,97.078178,0.000000,6.508389,98.000000,1.117275,4.356228,529.937396,0.000000e+00,6.714073,5.880277,4.321103,858.748809,1.173575,0.000000,4.578510,0.000000,559.272859,0.077352,-1.262651
25%,98.750000,545.825307,90.000000,13.470451,160.000000,4.702552,8.769181,583.363796,4.627258e+05,14.923421,11.121122,4.482384,887.174583,2.005021,0.000000,6.234717,45.000000,625.327743,0.365881,14.711926
50%,3559.500000,842.055177,3487.000000,16.295053,164.000000,6.983717,10.119274,615.240491,1.394034e+07,19.046641,13.846186,4.543375,890.031317,2.776068,74.500000,6.912886,553.000000,661.170690,0.574328,16.942795
75%,3865.250000,1169.875976,3861.250000,19.721242,169.000000,8.940686,11.774199,659.564239,1.488926e+07,19.977972,15.900814,4.646584,896.489977,4.089900,613.750000,7.834167,3756.250000,668.054192,0.797025,19.368358
max,4296.000000,1631.918408,4380.000000,24.508596,173.000000,12.312371,14.913641,742.725523,1.774067e+07,25.232161,20.290997,6.635675,918.084739,12.327319,4155.000000,10.253523,4457.000000,763.257466,1.377925,30.789863

In [10]:
# Adressing the class imbalance using SMOTE

stratified_shuffled_split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_indx, test_indx in stratified_shuffled_split.split(X_hot_rolling_selected, Y_hot_rolling):
    
    X_train_hot_rolling, X_test_hot_rolling = X_hot_rolling_selected.iloc[train_indx], X_hot_rolling_selected.iloc[test_indx]
    y_train_hot_rolling, y_test_hot_rolling = Y_hot_rolling[train_indx], Y_hot_rolling[test_indx]
    

print(f"Train defect ratio : {y_train_hot_rolling.mean():.4f}")
print(f"Test defect ratio : {y_test_hot_rolling.mean():.4f}")

# Applying SMOTE to the training data

smote = SMOTE(random_state=42, sampling_strategy=0.3)
X_train_hot_rolling_smote, y_train_hot_rolling_smote = smote.fit_resample(X_train_hot_rolling, y_train_hot_rolling)

print(f"Shape of training data after SMOTE: {X_train_hot_rolling_smote.shape}")
print(f"Defect ratio of training data after SMOTE: {y_train_hot_rolling_smote.mean():.4f}")

Train defect ratio : 0.0490
Test defect ratio : 0.0480
Shape of training data after SMOTE: (1336, 20)
Defect ratio of training data after SMOTE: 0.2305

### Model Preparation

In [11]:
# calculating scale_pos_weight as the ratio of the negative to positive samples

from sklearn.metrics import recall_score, precision_score, f1_score, roc_auc_score, precision_recall_curve, confusion_matrix

scale_pos_weight = (y_train_hot_rolling == 0).sum() / (y_train_hot_rolling == 1).sum()
print(f"Scale pos weight : {scale_pos_weight:.4f}")


xgb_classifier = xgb.XGBClassifier(
    scale_pos_weight = scale_pos_weight,
    eval_metric = 'logloss',
    random_state = 42,
    use_label_encoder = False
)

xgb_classifier.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Evaluating on the test set
y_pred_xgb = xgb_classifier.predict(X_test_hot_rolling)

print("Baseline XGBoost Classifier Performance : ")
print(f"Recall : {recall_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"Precision : {precision_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"F1 Score : {f1_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"ROC AUC Score : {roc_auc_score(y_test_hot_rolling, y_pred_xgb):.4f}")

Scale pos weight : 19.3962
Baseline XGBoost Classifier Performance :
Recall : 0.4615
Precision : 0.2609
F1 Score : 0.3333
ROC AUC Score : 0.6978

In [12]:
## Hyperparameter Tuning using GridSearchCV

import optuna
from sklearn.model_selection import GridSearchCV, cross_val_predict

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 800, step=50),
        'max_depth': trial.suggest_int('max_depth', 4, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 0.1),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.5, 2.0),
        'scale_pos_weight': trial.suggest_int('scale_pos_weight', 50, 150),
        'eval_metric': 'logloss',
        'random_state': 42,
        'use_label_encoder': False
    }
    
    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    recall_scores = []
    precision_scores = []
    
    for train_indx, val_indx in skf.split(X_train_hot_rolling_smote, y_train_hot_rolling_smote):
        X_train_fold, X_val_fold = X_train_hot_rolling_smote.iloc[train_indx], X_train_hot_rolling_smote.iloc[val_indx]
        y_train_fold, y_val_fold = y_train_hot_rolling_smote.iloc[train_indx], y_train_hot_rolling_smote.iloc[val_indx]
        
        model = xgb.XGBClassifier(**params)
        model.fit(X_train_fold, y_train_fold)
        
        y_val_pred = model.predict(X_val_fold)
        recall_scores.append(recall_score(y_val_fold, y_val_pred))
        precision_scores.append(precision_score(y_val_fold, y_val_pred))
        
        # using f2 score as the optimization metric to give more weight to recall
        
        f2_scores = (5 * np.mean(recall_scores) * np.mean(precision_scores)) / (4 * np.mean(precision_scores) + np.mean(recall_scores) + 1e-8)
        
        return f2_scores

In [13]:
%pip install --upgrade xgboost

Requirement already satisfied: xgboost in ./.venv/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [14]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50, show_progress_bar=True)
best_params = study.best_params
print("Best Hyperparameters : ", best_params)

# Training final XGBoost model with the best hyperparameters
xgb_final_classifier = xgb.XGBClassifier(**best_params, use_label_encoder=False)
xgb_final_classifier.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Cross validation with best model (Stratified K-Fold)


skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_recall = []
cv_precision = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_hot_rolling_smote, y_train_hot_rolling_smote)):
    X_train_fold, X_val_fold = X_train_hot_rolling_smote.iloc[train_idx], X_train_hot_rolling_smote.iloc[val_idx]
    y_train_fold, y_val_fold = y_train_hot_rolling_smote.iloc[train_idx], y_train_hot_rolling_smote.iloc[val_idx]
    
    model = xgb.XGBClassifier(**best_params, use_label_encoder=False)
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict(X_val_fold)
    cv_recall.append(recall_score(y_val_fold, y_pred))
    cv_precision.append(precision_score(y_val_fold, y_pred))
    
    print(f"Fold {fold+1} -  Recall: {cv_recall[-1]:.4f}, Precision: {cv_precision[-1]:.4f}")
    
print(f"CV Average Recall: {np.mean(cv_recall):.4f} (+/- {np.std(cv_recall):.4f})")
print(f"CV Average Precision: {np.mean(cv_precision):.4f} (+/- {np.std(cv_precision):.4f})")

[I 2026-05-30 20:45:36,545] A new study created in memory with name: no-name-d2cb01da-7b95-4c07-9a65-366a881bd4be
Best trial: 0. Best value: 0.885036:   2%|▏         | 1/50 [00:00<00:43,  1.14it/s]

[I 2026-05-30 20:45:37,429] Trial 0 finished with value: 0.8850364940180617 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.012679121823787368, 'subsample': 0.7823185623925358, 'colsample_bytree': 0.7043040584650825, 'min_child_weight': 6, 'gamma': 0.35108915219112624, 'reg_alpha': 0.06783824318373725, 'reg_lambda': 1.3776293608097994, 'scale_pos_weight': 98}. Best is trial 0 with value: 0.8850364940180617.

Best trial: 0. Best value: 0.885036:   4%|▍         | 2/50 [00:01<00:28,  1.69it/s]

[I 2026-05-30 20:45:37,821] Trial 1 finished with value: 0.8874045780519784 and parameters: {'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.06722086919791677, 'subsample': 0.6289892345337543, 'colsample_bytree': 0.7088871271545676, 'min_child_weight': 1, 'gamma': 0.2772170707853972, 'reg_alpha': 0.09673635635876669, 'reg_lambda': 1.6184682089505251, 'scale_pos_weight': 61}. Best is trial 0 with value: 0.8850364940180617.

Best trial: 2. Best value: 0.880682:   6%|▌         | 3/50 [00:01<00:23,  1.98it/s]

[I 2026-05-30 20:45:38,220] Trial 2 finished with value: 0.8806818160389406 and parameters: {'n_estimators': 450, 'max_depth': 7, 'learning_rate': 0.053248633069204944, 'subsample': 0.7731809052593758, 'colsample_bytree': 0.8285562632476289, 'min_child_weight': 4, 'gamma': 0.09982204019148244, 'reg_alpha': 0.06802082387306166, 'reg_lambda': 1.1903384056279342, 'scale_pos_weight': 68}. Best is trial 2 with value: 0.8806818160389406.

Best trial: 2. Best value: 0.880682:   8%|▊         | 4/50 [00:02<00:25,  1.83it/s]

[I 2026-05-30 20:45:38,831] Trial 3 finished with value: 0.8851224083726119 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.02238414000449148, 'subsample': 0.8877530210487635, 'colsample_bytree': 0.7204717845445827, 'min_child_weight': 4, 'gamma': 0.4259070423955856, 'reg_alpha': 0.0492328465654425, 'reg_lambda': 0.8647376148432822, 'scale_pos_weight': 65}. Best is trial 2 with value: 0.8806818160389406.

Best trial: 4. Best value: 0.867993:  10%|█         | 5/50 [00:02<00:21,  2.08it/s]

[I 2026-05-30 20:45:39,193] Trial 4 finished with value: 0.8679927643524226 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.02667572963950376, 'subsample': 0.7628949639335194, 'colsample_bytree': 0.8847398382829137, 'min_child_weight': 9, 'gamma': 0.08673295046164209, 'reg_alpha': 0.08181731827644377, 'reg_lambda': 0.9213388082544531, 'scale_pos_weight': 134}. Best is trial 4 with value: 0.8679927643524226.

Best trial: 5. Best value: 0.860215:  12%|█▏        | 6/50 [00:03<00:26,  1.67it/s]

[I 2026-05-30 20:45:40,020] Trial 5 finished with value: 0.8602150513485823 and parameters: {'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.013411952269044418, 'subsample': 0.6655617142977597, 'colsample_bytree': 0.8477305433145353, 'min_child_weight': 10, 'gamma': 0.30096810699189036, 'reg_alpha': 0.09392089350184867, 'reg_lambda': 1.4716475175072905, 'scale_pos_weight': 80}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  14%|█▍        | 7/50 [00:03<00:24,  1.74it/s]

[I 2026-05-30 20:45:40,550] Trial 6 finished with value: 0.8938547463709691 and parameters: {'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.036116711517817625, 'subsample': 0.874393638202706, 'colsample_bytree': 0.7357702181137882, 'min_child_weight': 6, 'gamma': 0.27476796538303827, 'reg_alpha': 0.017016346008132278, 'reg_lambda': 1.659471480801952, 'scale_pos_weight': 139}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  16%|█▌        | 8/50 [00:04<00:22,  1.90it/s]

[I 2026-05-30 20:45:40,971] Trial 7 finished with value: 0.8955223858369067 and parameters: {'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.06425145225240997, 'subsample': 0.6818648518233661, 'colsample_bytree': 0.6247561751384973, 'min_child_weight': 8, 'gamma': 0.22805599903994384, 'reg_alpha': 0.029317435359003254, 'reg_lambda': 0.5471887281565246, 'scale_pos_weight': 97}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  18%|█▊        | 9/50 [00:05<00:22,  1.84it/s]

[I 2026-05-30 20:45:41,555] Trial 8 finished with value: 0.8901515130086376 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.03466169855320599, 'subsample': 0.8369154774665456, 'colsample_bytree': 0.6087745942415042, 'min_child_weight': 3, 'gamma': 0.05646138934016598, 'reg_alpha': 0.09075895309179771, 'reg_lambda': 1.3351342585383592, 'scale_pos_weight': 68}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  20%|██        | 10/50 [00:05<00:23,  1.67it/s]

[I 2026-05-30 20:45:42,270] Trial 9 finished with value: 0.8888888866282578 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.030166275942879735, 'subsample': 0.6464343742053297, 'colsample_bytree': 0.7453884880139505, 'min_child_weight': 9, 'gamma': 0.1455561073979677, 'reg_alpha': 0.08889917921903895, 'reg_lambda': 1.2272695933889008, 'scale_pos_weight': 103}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  22%|██▏       | 11/50 [00:06<00:23,  1.63it/s]

[I 2026-05-30 20:45:42,924] Trial 10 finished with value: 0.8813263500051778 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.011787731277046656, 'subsample': 0.6985362538661183, 'colsample_bytree': 0.8124423188838065, 'min_child_weight': 10, 'gamma': 0.49543400239819774, 'reg_alpha': 0.0023558437640745777, 'reg_lambda': 1.8665950934974727, 'scale_pos_weight': 117}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 5. Best value: 0.860215:  24%|██▍       | 12/50 [00:06<00:21,  1.81it/s]

[I 2026-05-30 20:45:43,336] Trial 11 finished with value: 0.8818342126845709 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.01956547927720172, 'subsample': 0.7243589854590228, 'colsample_bytree': 0.8885899184562867, 'min_child_weight': 8, 'gamma': 0.0020872787880011068, 'reg_alpha': 0.06923567049623136, 'reg_lambda': 0.914499826118318, 'scale_pos_weight': 148}. Best is trial 5 with value: 0.8602150513485823.

Best trial: 12. Best value: 0.859107:  26%|██▌       | 13/50 [00:07<00:17,  2.12it/s]

[I 2026-05-30 20:45:43,621] Trial 12 finished with value: 0.8591065266249217 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.016818167920376655, 'subsample': 0.6022982762004342, 'colsample_bytree': 0.8979208887781925, 'min_child_weight': 10, 'gamma': 0.1957988366814597, 'reg_alpha': 0.07868117439539751, 'reg_lambda': 0.8248371720563418, 'scale_pos_weight': 125}. Best is trial 12 with value: 0.8591065266249217.

Best trial: 12. Best value: 0.859107:  28%|██▊       | 14/50 [00:07<00:15,  2.29it/s]

[I 2026-05-30 20:45:43,974] Trial 13 finished with value: 0.870337475344119 and parameters: {'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.01611962224496679, 'subsample': 0.6014158086433607, 'colsample_bytree': 0.8338836831390232, 'min_child_weight': 10, 'gamma': 0.20840082581619673, 'reg_alpha': 0.04925485790088347, 'reg_lambda': 0.593392154142445, 'scale_pos_weight': 83}. Best is trial 12 with value: 0.8591065266249217.

Best trial: 14. Best value: 0.85:  30%|███       | 15/50 [00:07<00:14,  2.48it/s]

[I 2026-05-30 20:45:44,301] Trial 14 finished with value: 0.8499999973105556 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.010118005868274223, 'subsample': 0.660930632402261, 'colsample_bytree': 0.7956910262629826, 'min_child_weight': 8, 'gamma': 0.32368062889302524, 'reg_alpha': 0.07829042183781958, 'reg_lambda': 1.9810285750745817, 'scale_pos_weight': 119}. Best is trial 14 with value: 0.8499999973105556.

Best trial: 14. Best value: 0.85:  32%|███▏      | 16/50 [00:08<00:13,  2.61it/s]

[I 2026-05-30 20:45:44,640] Trial 15 finished with value: 0.8514190290354542 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.010199329701681317, 'subsample': 0.6027484124051417, 'colsample_bytree': 0.7748141825957104, 'min_child_weight': 7, 'gamma': 0.37404989219854873, 'reg_alpha': 0.0762025254266939, 'reg_lambda': 1.9046597258754188, 'scale_pos_weight': 119}. Best is trial 14 with value: 0.8499999973105556.

Best trial: 14. Best value: 0.85:  34%|███▍      | 17/50 [00:08<00:12,  2.61it/s]

[I 2026-05-30 20:45:45,020] Trial 16 finished with value: 0.8737024195863915 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.0126623708098899, 'subsample': 0.711112467029256, 'colsample_bytree': 0.7836915998610485, 'min_child_weight': 7, 'gamma': 0.3643625727310834, 'reg_alpha': 0.058933185805502414, 'reg_lambda': 1.9393178314256827, 'scale_pos_weight': 115}. Best is trial 14 with value: 0.8499999973105556.

Best trial: 14. Best value: 0.85:  36%|███▌      | 18/50 [00:08<00:12,  2.46it/s]

[I 2026-05-30 20:45:45,480] Trial 17 finished with value: 0.8963093120896279 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.011005049707093635, 'subsample': 0.6383922667263553, 'colsample_bytree': 0.77950120063792, 'min_child_weight': 7, 'gamma': 0.39420390228792707, 'reg_alpha': 0.041500730872564326, 'reg_lambda': 1.7805043201102921, 'scale_pos_weight': 120}. Best is trial 14 with value: 0.8499999973105556.

Best trial: 18. Best value: 0.844371:  38%|███▊      | 19/50 [00:09<00:11,  2.75it/s]

[I 2026-05-30 20:45:45,747] Trial 18 finished with value: 0.8443708582167451 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.010448479572543128, 'subsample': 0.662468270241971, 'colsample_bytree': 0.6670740287661192, 'min_child_weight': 5, 'gamma': 0.4657425711456824, 'reg_alpha': 0.07668596756251263, 'reg_lambda': 1.9573798476575106, 'scale_pos_weight': 106}. Best is trial 18 with value: 0.8443708582167451.

Best trial: 18. Best value: 0.844371:  40%|████      | 20/50 [00:09<00:09,  3.01it/s]

[I 2026-05-30 20:45:46,005] Trial 19 finished with value: 0.9039548000863593 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.09791208174830385, 'subsample': 0.7366879779739645, 'colsample_bytree': 0.6538176034706692, 'min_child_weight': 5, 'gamma': 0.4444260826715038, 'reg_alpha': 0.05900891617629643, 'reg_lambda': 1.991935331799901, 'scale_pos_weight': 108}. Best is trial 18 with value: 0.8443708582167451.

Best trial: 18. Best value: 0.844371:  42%|████▏     | 21/50 [00:09<00:09,  2.94it/s]

[I 2026-05-30 20:45:46,363] Trial 20 finished with value: 0.8886894051334574 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.01590241670726784, 'subsample': 0.8140750840313628, 'colsample_bytree': 0.689120482913576, 'min_child_weight': 2, 'gamma': 0.4936639692596962, 'reg_alpha': 0.03576243077482472, 'reg_lambda': 1.7213883658102787, 'scale_pos_weight': 88}. Best is trial 18 with value: 0.8443708582167451.

Best trial: 18. Best value: 0.844371:  44%|████▍     | 22/50 [00:10<00:09,  2.97it/s]

[I 2026-05-30 20:45:46,693] Trial 21 finished with value: 0.8673469361539174 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.010278076652360793, 'subsample': 0.6649976354961014, 'colsample_bytree': 0.7760151874425953, 'min_child_weight': 5, 'gamma': 0.34495907122061964, 'reg_alpha': 0.08047501786460631, 'reg_lambda': 1.8253722885209556, 'scale_pos_weight': 129}. Best is trial 18 with value: 0.8443708582167451.

Best trial: 22. Best value: 0.814696:  46%|████▌     | 23/50 [00:10<00:08,  3.25it/s]

[I 2026-05-30 20:45:46,931] Trial 22 finished with value: 0.814696482810634 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.010574897310246738, 'subsample': 0.6222092160980853, 'colsample_bytree': 0.6775731008153905, 'min_child_weight': 8, 'gamma': 0.44079853835650235, 'reg_alpha': 0.07648611346596619, 'reg_lambda': 1.997057108178758, 'scale_pos_weight': 109}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  48%|████▊     | 24/50 [00:10<00:07,  3.50it/s]

[I 2026-05-30 20:45:47,166] Trial 23 finished with value: 0.8571428544807571 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.015246138602564744, 'subsample': 0.6315092644915556, 'colsample_bytree': 0.6658256258751422, 'min_child_weight': 8, 'gamma': 0.44921653504005665, 'reg_alpha': 0.06031110682155439, 'reg_lambda': 1.5911360459201163, 'scale_pos_weight': 110}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  50%|█████     | 25/50 [00:10<00:07,  3.41it/s]

[I 2026-05-30 20:45:47,478] Trial 24 finished with value: 0.8839285689980868 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.02006311909175557, 'subsample': 0.6876318921461877, 'colsample_bytree': 0.6559007137262797, 'min_child_weight': 6, 'gamma': 0.4178085633462465, 'reg_alpha': 0.08521288085438358, 'reg_lambda': 1.777127390415096, 'scale_pos_weight': 90}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  52%|█████▏    | 26/50 [00:11<00:06,  3.59it/s]

[I 2026-05-30 20:45:47,723] Trial 25 finished with value: 0.8658743607001307 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.0138487294880875, 'subsample': 0.6574622180439671, 'colsample_bytree': 0.6768846531584064, 'min_child_weight': 4, 'gamma': 0.31151906002531937, 'reg_alpha': 0.0728893413587505, 'reg_lambda': 1.9790992527644324, 'scale_pos_weight': 106}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  54%|█████▍    | 27/50 [00:11<00:07,  3.01it/s]

[I 2026-05-30 20:45:48,181] Trial 26 finished with value: 0.8703071646259714 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.01024922957999585, 'subsample': 0.6228519316207934, 'colsample_bytree': 0.6258015912745506, 'min_child_weight': 9, 'gamma': 0.46246324032415015, 'reg_alpha': 0.09790505751294465, 'reg_lambda': 1.4645515728670497, 'scale_pos_weight': 141}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  56%|█████▌    | 28/50 [00:11<00:07,  3.06it/s]

[I 2026-05-30 20:45:48,492] Trial 27 finished with value: 0.8875219658681868 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.018817441699266302, 'subsample': 0.6807933472209449, 'colsample_bytree': 0.6327556506701608, 'min_child_weight': 7, 'gamma': 0.3995250525536938, 'reg_alpha': 0.06150323162305315, 'reg_lambda': 1.8579232810801145, 'scale_pos_weight': 127}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  58%|█████▊    | 29/50 [00:12<00:06,  3.07it/s]

[I 2026-05-30 20:45:48,818] Trial 28 finished with value: 0.8866544766526074 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.02532327478689045, 'subsample': 0.7112569435555546, 'colsample_bytree': 0.6925342168907034, 'min_child_weight': 5, 'gamma': 0.4728138584090865, 'reg_alpha': 0.08677841763455596, 'reg_lambda': 1.9990874336777722, 'scale_pos_weight': 97}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  60%|██████    | 30/50 [00:12<00:06,  2.89it/s]

[I 2026-05-30 20:45:49,210] Trial 29 finished with value: 0.8890845045520482 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.012566181240221635, 'subsample': 0.7483704738059596, 'colsample_bytree': 0.7219866061192711, 'min_child_weight': 6, 'gamma': 0.3250335161276282, 'reg_alpha': 0.06529079547476911, 'reg_lambda': 1.525919421214958, 'scale_pos_weight': 112}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  62%|██████▏   | 31/50 [00:12<00:06,  3.06it/s]

[I 2026-05-30 20:45:49,492] Trial 30 finished with value: 0.8791208768060084 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.04017624786499791, 'subsample': 0.6512978784240645, 'colsample_bytree': 0.7587755760471255, 'min_child_weight': 8, 'gamma': 0.34819914106845307, 'reg_alpha': 0.07380621093061335, 'reg_lambda': 1.085751826967058, 'scale_pos_weight': 101}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  64%|██████▍   | 32/50 [00:13<00:06,  2.90it/s]

[I 2026-05-30 20:45:49,878] Trial 31 finished with value: 0.8571428544807571 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.011500536503841141, 'subsample': 0.6128810951711118, 'colsample_bytree': 0.8145577722856705, 'min_child_weight': 7, 'gamma': 0.3901893880636739, 'reg_alpha': 0.07627944957085123, 'reg_lambda': 1.8873003693239854, 'scale_pos_weight': 122}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  66%|██████▌   | 33/50 [00:13<00:05,  2.96it/s]

[I 2026-05-30 20:45:50,200] Trial 32 finished with value: 0.8499999973105556 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.010012762757178603, 'subsample': 0.6219601824626232, 'colsample_bytree': 0.8052790237672877, 'min_child_weight': 7, 'gamma': 0.3696130215127111, 'reg_alpha': 0.05380303354042429, 'reg_lambda': 1.7451175741679772, 'scale_pos_weight': 115}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  68%|██████▊   | 34/50 [00:14<00:05,  2.92it/s]

[I 2026-05-30 20:45:50,553] Trial 33 finished with value: 0.8844133074709929 and parameters: {'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.013841859426622057, 'subsample': 0.6370385173202487, 'colsample_bytree': 0.8033299831230276, 'min_child_weight': 6, 'gamma': 0.2682392209945089, 'reg_alpha': 0.05122008973823741, 'reg_lambda': 1.7076892697342865, 'scale_pos_weight': 132}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  70%|███████   | 35/50 [00:14<00:05,  2.99it/s]

[I 2026-05-30 20:45:50,868] Trial 34 finished with value: 0.8673469361539174 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.012032824679124638, 'subsample': 0.669896611727176, 'colsample_bytree': 0.853590663112958, 'min_child_weight': 9, 'gamma': 0.42140012754072664, 'reg_alpha': 0.0526431657148642, 'reg_lambda': 1.78254565849245, 'scale_pos_weight': 93}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  72%|███████▏  | 36/50 [00:14<00:04,  3.26it/s]

[I 2026-05-30 20:45:51,111] Trial 35 finished with value: 0.8360655710300995 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.010044333850786772, 'subsample': 0.6207419095807214, 'colsample_bytree': 0.7075012620294068, 'min_child_weight': 8, 'gamma': 0.3364384564015068, 'reg_alpha': 0.06873260628765245, 'reg_lambda': 1.5873651225022305, 'scale_pos_weight': 55}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  74%|███████▍  | 37/50 [00:14<00:04,  3.17it/s]

[I 2026-05-30 20:45:51,447] Trial 36 finished with value: 0.8906525548362464 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.0143702193168629, 'subsample': 0.64820345815215, 'colsample_bytree': 0.7069414464900313, 'min_child_weight': 8, 'gamma': 0.32924090534224865, 'reg_alpha': 0.0688413487659428, 'reg_lambda': 1.5806465877494338, 'scale_pos_weight': 53}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  76%|███████▌  | 38/50 [00:15<00:04,  2.76it/s]

[I 2026-05-30 20:45:51,919] Trial 37 finished with value: 0.8931860013951209 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.017465978466748692, 'subsample': 0.7922611700275739, 'colsample_bytree': 0.7237364965876917, 'min_child_weight': 1, 'gamma': 0.2981468196244069, 'reg_alpha': 0.08100777573138883, 'reg_lambda': 1.3247292218076376, 'scale_pos_weight': 76}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  78%|███████▊  | 39/50 [00:15<00:03,  2.87it/s]

[I 2026-05-30 20:45:52,235] Trial 38 finished with value: 0.8971962594691238 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.04571389527715103, 'subsample': 0.6175937346390014, 'colsample_bytree': 0.6945741441016682, 'min_child_weight': 4, 'gamma': 0.23512054290838058, 'reg_alpha': 0.09503530640722437, 'reg_lambda': 1.126018832552935, 'scale_pos_weight': 50}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  80%|████████  | 40/50 [00:16<00:04,  2.35it/s]

[I 2026-05-30 20:45:52,838] Trial 39 finished with value: 0.8878504650766006 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.023467541821443703, 'subsample': 0.6980500982714164, 'colsample_bytree': 0.6415919837024832, 'min_child_weight': 3, 'gamma': 0.4260693824184438, 'reg_alpha': 0.0836306503352231, 'reg_lambda': 1.6442206886370827, 'scale_pos_weight': 73}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  82%|████████▏ | 41/50 [00:16<00:03,  2.25it/s]

[I 2026-05-30 20:45:53,328] Trial 40 finished with value: 0.8749999975695155 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.011568407078615206, 'subsample': 0.6693584048056146, 'colsample_bytree': 0.6762734538227095, 'min_child_weight': 9, 'gamma': 0.2575476834793564, 'reg_alpha': 0.06541268667461186, 'reg_lambda': 1.4141750306204706, 'scale_pos_weight': 60}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  84%|████████▍ | 42/50 [00:17<00:03,  2.45it/s]

[I 2026-05-30 20:45:53,653] Trial 41 finished with value: 0.8279220751533776 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.010269818010658628, 'subsample': 0.6237592469275449, 'colsample_bytree': 0.7569822862903584, 'min_child_weight': 8, 'gamma': 0.36499020956605976, 'reg_alpha': 0.04279555426281833, 'reg_lambda': 1.6895268962233798, 'scale_pos_weight': 113}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  86%|████████▌ | 43/50 [00:17<00:02,  2.71it/s]

[I 2026-05-30 20:45:53,929] Trial 42 finished with value: 0.8644067770275783 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.013164571392844812, 'subsample': 0.6320212536019908, 'colsample_bytree': 0.7520722819953821, 'min_child_weight': 8, 'gamma': 0.2879333360949571, 'reg_alpha': 0.03896032246208617, 'reg_lambda': 1.9069125093830517, 'scale_pos_weight': 103}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  88%|████████▊ | 44/50 [00:17<00:02,  3.00it/s]

[I 2026-05-30 20:45:54,181] Trial 43 finished with value: 0.8252427156688242 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.011384704259783709, 'subsample': 0.6487542456322047, 'colsample_bytree': 0.7369393184765293, 'min_child_weight': 9, 'gamma': 0.40441921594304725, 'reg_alpha': 0.030514465996678092, 'reg_lambda': 1.66555820017583, 'scale_pos_weight': 112}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  90%|█████████ | 45/50 [00:17<00:01,  3.26it/s]

[I 2026-05-30 20:45:54,424] Trial 44 finished with value: 0.8225806423746099 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.011335463293496006, 'subsample': 0.6161893022570759, 'colsample_bytree': 0.735602747648712, 'min_child_weight': 9, 'gamma': 0.4815429645528822, 'reg_alpha': 0.022034073420189933, 'reg_lambda': 1.6672932507055367, 'scale_pos_weight': 111}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  92%|█████████▏| 46/50 [00:18<00:01,  3.48it/s]

[I 2026-05-30 20:45:54,668] Trial 45 finished with value: 0.8225806423746099 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.011718541257809974, 'subsample': 0.6131125954687957, 'colsample_bytree': 0.7404343418749262, 'min_child_weight': 9, 'gamma': 0.43350953325974173, 'reg_alpha': 0.023070007397312554, 'reg_lambda': 1.6706993672587227, 'scale_pos_weight': 112}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  94%|█████████▍| 47/50 [00:18<00:01,  2.69it/s]

[I 2026-05-30 20:45:55,234] Trial 46 finished with value: 0.8633093501190414 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.014229783301763051, 'subsample': 0.6125060894146137, 'colsample_bytree': 0.7323662353002279, 'min_child_weight': 9, 'gamma': 0.49762297307404296, 'reg_alpha': 0.01691027517363932, 'reg_lambda': 1.5038441568379253, 'scale_pos_weight': 111}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  96%|█████████▌| 48/50 [00:18<00:00,  3.02it/s]

[I 2026-05-30 20:45:55,470] Trial 47 finished with value: 0.8225806423746099 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.011937625750663311, 'subsample': 0.6412165714781606, 'colsample_bytree': 0.7581189011505405, 'min_child_weight': 10, 'gamma': 0.43563642580859496, 'reg_alpha': 0.022779449450649424, 'reg_lambda': 1.6883088486660718, 'scale_pos_weight': 124}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696:  98%|█████████▊| 49/50 [00:19<00:00,  3.31it/s]

[I 2026-05-30 20:45:55,706] Trial 48 finished with value: 0.8629441597972694 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.017936084367096285, 'subsample': 0.6388594847584613, 'colsample_bytree': 0.7378782836696735, 'min_child_weight': 10, 'gamma': 0.4394296343868231, 'reg_alpha': 0.023556456756210164, 'reg_lambda': 1.3909340454215247, 'scale_pos_weight': 124}. Best is trial 22 with value: 0.814696482810634.

Best trial: 22. Best value: 0.814696: 100%|██████████| 50/50 [00:19<00:00,  2.57it/s]

[I 2026-05-30 20:45:56,009] Trial 49 finished with value: 0.8388157867430965 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.01244678106775338, 'subsample': 0.6063673908879321, 'colsample_bytree': 0.7652111040185318, 'min_child_weight': 10, 'gamma': 0.47649577756966377, 'reg_alpha': 0.0057321852893319515, 'reg_lambda': 1.6323645051400117, 'scale_pos_weight': 138}. Best is trial 22 with value: 0.814696482810634.
Best Hyperparameters :  {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.010574897310246738, 'subsample': 0.6222092160980853, 'colsample_bytree': 0.6775731008153905, 'min_child_weight': 8, 'gamma': 0.44079853835650235, 'reg_alpha': 0.07648611346596619, 'reg_lambda': 1.997057108178758, 'scale_pos_weight': 109}
Fold 1 -  Recall: 0.9839, Precision: 0.5126
Fold 2 -  Recall: 1.0000, Precision: 0.4357
Fold 3 -  Recall: 0.9836, Precision: 0.4651
Fold 4 -  Recall: 1.0000, Precision: 0.4397
Fold 5 -  Recall: 1.0000, Precision: 0.4161
CV Average Recall: 0.9935 (+/- 0.0080)
CV Average Precision: 0.4539 (+/- 0.0333)

### Ensemble: LightGBM + Logistics Regression

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier, StackingClassifier

lgb_model = lgb.LGBMClassifier(
    is_unbalance=True,
    learning_rate=0.05,
    n_estimators=500,
    max_depth=5,
    num_leaves=31,
    random_state=42
)

lgb_model.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Training a simple logistic regression model for comparision (with SMOTE data)
log_reg_model = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
log_reg_model.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Soft voting ensemble of XGBoost, LightGBM and Logistic Regression
voting_clf = VotingClassifier(
    estimators=[
        ('xgb', xgb_final_classifier),
        ('lgb', lgb_model),
        ('log_reg', log_reg_model)
    ],
    voting='soft',
    weights=[1.5, 1.2, 0.8]
)

voting_clf.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Stacking ensemble using the predictions of the base models which is used as the features
# for the meta model (Logistic Regression)

stacking_clf = StackingClassifier(
    estimators=[
        ('xgb', xgb_final_classifier),
        ('lgb', lgb_model)
    ],
    final_estimator=LogisticRegression(C=1.0),
    cv=5,
    stack_method='predict_proba'
)

stacking_clf.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Evaluating both the ensemble models on test set with threshold 0.5

for name, model in [('Voting', voting_clf), ('Stacking', stacking_clf)]:
    y_pred = model.predict(X_test_hot_rolling)
    print(f"\n{name} Ensemble Performance : ")
    print(f"Recall : {recall_score(y_test_hot_rolling, y_pred):.4f}")
    print(f"Precision : {precision_score(y_test_hot_rolling, y_pred):.4f}")

[LightGBM] [Info] Number of positive: 308, number of negative: 1028
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000207 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5099
[LightGBM] [Info] Number of data points in the train set: 1336, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.230539 -> initscore=-1.205271
[LightGBM] [Info] Start training from score -1.205271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Evaluation - Achieving 100% Recall and >90% Accuracy

In [16]:
def evaluate_model(model, X_test, y_test, threshold=0.5, model_name="Model"):
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_pred_proba >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    recall = tp / (tp + fn) if (tp+fn) > 0 else 0
    precision = tp / (tp + fp) if (tp+fp) > 0 else 0
    print(f"\n{model_name} - Threshold {threshold:.2f}")
    print(f"Confusion Matrix: TP={tp}, FP={fp}, FN={fn}, TN={tn}")
    print(f"Recall: {recall:.4f}  (Target: 1.0000)")
    print(f"Precision: {precision:.4f} (Target: >0.90)")
    return recall, precision, y_pred_proba


best_model = stacking_clf
evaluate_model(best_model, X_test_hot_rolling, y_test_hot_rolling, threshold=0.5)

Model - Threshold 0.50
Confusion Matrix: TP=4, FP=14, FN=9, TN=244
Recall: 0.3077  (Target: 1.0000)
Precision: 0.2222 (Target: >0.90)

(np.float64(0.3076923076923077),
 np.float64(0.2222222222222222),
 array([0.0073686 , 0.00737687, 0.00718616, 0.00809105, 0.01772461,
        0.11323958, 0.00700309, 0.00759376, 0.00758373, 0.00708978,
        0.8238935 , 0.03541479, 0.00743323, 0.00877205, 0.00730356,
        0.00748442, 0.00898143, 0.01938857, 0.00708784, 0.00846305,
        0.06047031, 0.875695  , 0.01122821, 0.00725583, 0.3131715 ,
        0.05161468, 0.78009033, 0.00718322, 0.11329924, 0.06130156,
        0.17154721, 0.00718388, 0.00731097, 0.00763854, 0.80818957,
        0.06007354, 0.00746108, 0.00822369, 0.08728204, 0.00914807,
        0.00771628, 0.00823401, 0.00716604, 0.03754698, 0.06125808,
        0.03446799, 0.78578983, 0.00724288, 0.00737813, 0.07448964,
        0.06222739, 0.04624693, 0.07253249, 0.02024354, 0.01379533,
        0.01916203, 0.06071588, 0.00742193, 0.82414707, 0.02723923,
        0.39015555, 0.13132257, 0.00745585, 0.0567231 , 0.00713594,
        0.00719123, 0.20104639, 0.00712613, 0.01208971, 0.00691756,
        0.08164377, 0.01023876, 0.02233792, 0.00745177, 0.00705561,
        0.01043365, 0.05171744, 0.08675239, 0.00700893, 0.00776199,
        0.00799742, 0.05439983, 0.03103829, 0.01354706, 0.5550558 ,
        0.01031597, 0.05074985, 0.01930544, 0.00712342, 0.04498879,
        0.00813712, 0.00977652, 0.06870276, 0.04307369, 0.00996608,
        0.00731986, 0.08336246, 0.77350071, 0.10027682, 0.09844584,
        0.01642731, 0.04092684, 0.47436034, 0.00829405, 0.06589362,
        0.00702338, 0.01264573, 0.01689498, 0.73014908, 0.00843125,
        0.00755017, 0.02601183, 0.00928987, 0.00719255, 0.00753065,
        0.01566455, 0.04648393, 0.0073784 , 0.0124071 , 0.01416924,
        0.00865212, 0.00721666, 0.00727902, 0.00864433, 0.00956602,
        0.01208221, 0.84768121, 0.00871835, 0.10570329, 0.0509681 ,
        0.00792812, 0.00714077, 0.04269499, 0.90076175, 0.02522049,
        0.0083518 , 0.0070771 , 0.01608906, 0.01130193, 0.09640661,
        0.00708434, 0.00863096, 0.11979138, 0.04585454, 0.00706847,
        0.00714616, 0.00736097, 0.07872516, 0.05313435, 0.04991923,
        0.00895965, 0.70465203, 0.06336947, 0.00739818, 0.01796302,
        0.03446595, 0.00736721, 0.00911491, 0.04744992, 0.02114871,
        0.02116334, 0.09588963, 0.03084155, 0.00698376, 0.14693733,
        0.00701923, 0.0094051 , 0.00737869, 0.15527599, 0.00800445,
        0.00937201, 0.00935395, 0.02691197, 0.00708382, 0.00711161,
        0.00726639, 0.01461655, 0.01417394, 0.71229151, 0.00791734,
        0.01610602, 0.00777168, 0.00743265, 0.90214111, 0.00720248,
        0.11002114, 0.04559709, 0.00707761, 0.00813902, 0.07562709,
        0.01144075, 0.01332834, 0.13082368, 0.00728376, 0.05628295,
        0.00940531, 0.08248528, 0.01267501, 0.6414594 , 0.00922811,
        0.02032513, 0.01994564, 0.00718382, 0.007566  , 0.11150027,
        0.63979867, 0.01988327, 0.0072394 , 0.01637119, 0.00813076,
        0.00823565, 0.00716544, 0.00707925, 0.00873834, 0.007727  ,
        0.07389066, 0.00783225, 0.08676292, 0.22745161, 0.19559669,
        0.01939151, 0.00719918, 0.0074298 , 0.08603448, 0.0383253 ,
        0.00805181, 0.00716266, 0.44651209, 0.04370699, 0.64579034,
        0.07770785, 0.00771068, 0.00816064, 0.00711167, 0.00763161,
        0.00742817, 0.00717789, 0.00857761, 0.04166276, 0.01602972,
        0.00756219, 0.08601673, 0.00711735, 0.04176459, 0.01795   ,
        0.00817362, 0.00750615, 0.80986297, 0.01585621, 0.0442042 ,
        0.04663428, 0.07330845, 0.00716096, 0.00702483, 0.00715242,
        0.0808077 , 0.00799936, 0.0073598 , 0.01583655, 0.0654078 ,
        0.00866171, 0.00736552, 0.00718202, 0.02393862, 0.04405745,
        0.00708164, 0.00726639, 0.0150664 , 0.24130287, 0.2469884 ,
        0.00877692]))

In [17]:
# Threshold tuning using Precision-Recall curve

from sklearn.model_selection import train_test_split

def find_optimal_threshold(model, X_val, y_val, target_recall=1.0, target_precision=0.9):
    y_proba = model.predict_proba(X_val)[:, 1]
    precisions, recalls, thresholds = precision_recall_curve(y_val, y_proba)
    # We need the highest threshold where recall >= target_recall and precision >= target_precision
    feasible = []
    for i in range(len(thresholds)):
        if recalls[i] >= target_recall - 1e-6 and precisions[i] >= target_precision - 1e-6:
            feasible.append((thresholds[i], recalls[i], precisions[i]))
    if feasible:
        # Among feasible, choose threshold that maximizes precision (or simply the one with highest precision)
        best = max(feasible, key=lambda x: x[2])   # highest precision
        return best[0], best[1], best[2]
    else:
        # No threshold satisfies both; find threshold that gives recall=1.0 with best precision
        recall_1_indices = [i for i, r in enumerate(recalls) if r >= target_recall - 1e-6]
        if recall_1_indices:
            best_idx = max(recall_1_indices, key=lambda i: precisions[i])
            return thresholds[best_idx], recalls[best_idx], precisions[best_idx]
        else:
            return 0.5, recalls[-1], precisions[-1]
        
        
X_train_final, X_val_thresh, y_train_final, y_val_thresh = train_test_split(
    X_train_hot_rolling_smote, 
    y_train_hot_rolling_smote, 
    test_size=0.2,
    stratify=y_train_hot_rolling_smote,
    random_state=42
)

# Retrain best model on X_train_final
final_model = stacking_clf 
final_model.fit(X_train_final, y_train_final)

opt_threshold, opt_recall, opt_precision = find_optimal_threshold(
    final_model, X_val_thresh, y_val_thresh, target_recall=1.0, target_precision=0.9
)
print(f"\nOptimal threshold: {opt_threshold:.3f} (Recall={opt_recall:.4f}, Precision={opt_precision:.4f})")


# Evaluate on test set with optimal threshold
_, _, y_proba_test = evaluate_model(final_model, X_test_hot_rolling, y_test_hot_rolling, threshold=opt_threshold, model_name="Final Model with Optimal Threshold")

[LightGBM] [Info] Number of positive: 246, number of negative: 822
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000219 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4929
[LightGBM] [Info] Number of data points in the train set: 1068, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.230337 -> initscore=-1.206409
[LightGBM] [Info] Start training from score -1.206409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [18]:

# Final Check: Guarantee Recall = 100% on test?

# If recall is still < 100%, we can try lowering threshold further until recall=1.0
def threshold_for_recall_1(model, X_val, y_val):
    y_proba = model.predict_proba(X_val)[:, 1]
    precisions, recalls, thresholds = precision_recall_curve(y_val, y_proba)
    for i in range(len(thresholds)):
        if recalls[i] >= 1.0 - 1e-6:
            return thresholds[i], precisions[i]
    return 0.1, precisions[-1]   # fallback

thresh_recall1, prec_at_thresh = threshold_for_recall_1(final_model, X_val_thresh, y_val_thresh)
print(f"\nThreshold for 100% recall: {thresh_recall1:.3f} (Precision = {prec_at_thresh:.4f})")

# Evaluate test set with that threshold
_, _, _ = evaluate_model(final_model, X_test_hot_rolling, y_test_hot_rolling, threshold=thresh_recall1, model_name="100% Recall Threshold")

Threshold for 100% recall: 0.009 (Precision = 0.2313)

100% Recall Threshold - Threshold 0.01
Confusion Matrix: TP=13, FP=258, FN=0, TN=0
Recall: 1.0000  (Target: 1.0000)
Precision: 0.0480 (Target: >0.90)

In [20]:
import joblib
joblib.dump(final_model, 'alpha_defect_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(imputer, 'imputer.pkl')
joblib.dump(top_20_features_hot_rolling, 'selected_features.pkl')

['selected_features.pkl']