In [1]:
%pip install xgboost imbalanced-learn scikit-learn pandas numpy matplotlib seaborn joblib lightgbm optuna

Requirement already satisfied: xgboost in ./.venv/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: imbalanced-learn in ./.venv/lib/python3.14/site-packages (0.14.1)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (2.4.6)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.14/site-packages (3.10.9)
Requirement already satisfied: seaborn in ./.venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: joblib in ./.venv/lib/python3.14/site-packages (1.5.3)
Requirement already satisfied: lightgbm in ./.venv/lib/python3.14/site-packages (4.6.0)
Requirement already satisfied: optuna in ./.venv/lib/python3.14/site-packages (4.8.0)
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in ./.venv/lib/python3.14/site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in ./.venv/lib/python3.14/site-packages (from imbalanced-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: alembic>=1.5.0 in ./.venv/lib/python3.14/site-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in ./.venv/lib/python3.14/site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in ./.venv/lib/python3.14/site-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in ./.venv/lib/python3.14/site-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in ./.venv/lib/python3.14/site-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in ./.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in ./.venv/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in ./.venv/lib/python3.14/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

### Data Preparation

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import KNNImputer, SimpleImputer
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import lightgbm as lgb
import warnings
warnings.filterwarnings('ignore')

In [3]:
hot_rolling_df = pd.read_csv('dataset/train.csv')
print(f"Hot Rolling Dataset Shape : {hot_rolling_df.shape}")
hot_rolling_df.head(20)

Hot Rolling Dataset Shape : (1352, 51)

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
0,487,854.787195,501.088868,414.841484,710.583316,662.072013,656.076977,547.040479,563.653582,495.296785,...,0.201645,0.047960,0.267467,0.052247,-0.893174,0.000000,0.028925,0.000534,0.010797,0.0
1,44,1056.526699,868.083321,622.879982,725.276469,665.235554,647.450550,552.333202,565.105074,493.310075,...,0.644403,0.000000,0.341870,0.153513,25.471899,0.002520,0.033281,0.028349,0.079602,0.0
2,192,1095.648362,668.112517,695.787904,716.773671,662.843475,657.542380,549.863867,546.210823,482.814753,...,0.486502,0.000000,0.202539,0.168192,-25.764196,0.002072,0.033878,0.000000,0.058266,0.0
3,1552,1050.943543,660.340015,440.280245,611.562496,628.081103,561.397721,456.816210,550.103433,378.353283,...,1.198010,0.020787,0.288786,0.329108,1.033840,0.000250,0.045490,0.039004,0.004850,0.0
4,1190,1091.640314,297.363775,842.665620,749.160886,652.992309,615.576656,608.364764,549.756758,487.753140,...,0.237231,0.000841,0.257281,0.112637,-11.130157,0.002376,0.031298,0.003623,0.018434,0.0
5,102,1060.742584,809.756675,675.882581,726.410383,672.159859,661.250928,555.468859,554.440758,492.462056,...,0.810914,0.043039,0.274467,0.250703,28.221606,0.002755,0.049610,0.001055,0.117253,0.0
6,900,1087.182781,513.823963,434.777529,727.732813,661.179522,606.946096,539.393969,532.864699,480.662740,...,0.565355,0.000846,0.341627,0.115135,8.942980,0.002918,0.051415,0.029154,0.084616,0.0
7,674,1082.185852,328.168651,395.732261,610.456744,650.491924,532.674335,467.587611,544.260627,486.572833,...,0.198847,0.001384,0.256416,0.042418,21.992259,0.000704,0.039402,0.000028,0.009336,0.0
8,572,1111.579895,909.156996,317.875943,731.479162,672.679098,663.639612,547.616420,571.662343,490.837575,...,0.518436,0.000000,0.215945,0.051108,-17.106723,0.000842,0.037112,0.002238,0.011166,0.0
9,1205,1037.383965,609.839905,513.596340,728.363034,645.250990,590.713451,601.842899,520.893575,484.417182,...,1.010123,0.000000,0.231285,0.010257,6.860036,0.002862,0.047626,0.032069,0.119772,0.0
10,1081,1083.697248,572.391786,671.363477,737.848661,650.785937,604.239124,546.626007,525.499437,478.915896,...,0.461687,0.001894,0.304753,0.073592,4.354575,0.001870,0.050725,0.001415,0.006052,0.0
11,314,1008.180963,709.665138,630.827271,605.168675,597.404223,546.726893,444.531271,550.249659,487.746522,...,0.879044,0.046486,0.272398,0.091139,13.197569,0.002377,0.033046,0.000545,0.145210,0.0
12,1228,1097.478596,567.979471,523.921210,623.240825,581.404728,563.013462,451.812520,540.824982,415.031696,...,0.838788,0.049190,0.221663,0.023326,3.498766,0.002354,0.042453,0.000000,0.148410,0.0
13,944,1102.735733,602.313220,520.071286,729.700843,664.951333,612.754181,558.214284,550.691257,492.340875,...,0.517536,0.002737,0.364665,0.146593,19.403038,0.001318,0.052653,0.001870,0.074739,0.0
14,516,1058.259850,203.672905,217.861576,735.985361,658.214744,655.293485,545.840209,560.555212,491.731852,...,0.610901,0.019341,0.223121,0.036305,26.023011,0.001399,0.045250,0.000000,0.003763,0.0
15,912,1078.860939,656.695718,566.652073,742.074991,660.117144,612.993051,547.970221,553.210440,474.479272,...,0.778340,0.012607,0.321385,0.136010,-0.939537,0.001794,0.050302,0.000695,0.019277,0.0
16,189,1080.264944,497.387805,635.200240,724.704393,668.621530,662.383468,550.844784,547.513319,487.717931,...,0.524678,0.000000,0.191361,0.165117,-17.519580,0.002364,0.050070,0.000000,0.053662,0.0
17,1016,1077.266535,440.590656,494.504324,735.538765,668.925677,612.806052,549.802155,544.383220,474.622249,...,0.742090,0.009886,0.184221,0.007917,-12.072707,0.000514,0.033293,0.002611,0.005861,0.0
18,1529,933.734873,801.510280,627.868619,737.419350,748.141192,712.865662,591.424888,538.684623,479.168138,...,0.519538,0.000695,0.164385,0.004205,1.666199,0.000000,0.046633,0.003317,0.067964,0.0
19,1619,1029.273576,812.375220,395.471733,610.271229,618.513558,585.045612,468.386640,460.249033,397.309193,...,1.223748,0.016347,0.217337,0.011733,4.047144,0.003039,0.049347,0.040050,0.125722,0.0

In [4]:
# Check for the missing values in the before starting to 'impute' in the  dataset
missing_values = hot_rolling_df.isnull().sum()
print("Missing values in each of the column features in the dataset : \n", missing_values)
hot_rolling_df.info()
hot_rolling_df.describe()

Missing values in each of the column features in the dataset :
 CoilID      0
X1          0
X2          0
X3          0
X4          0
X5          0
X6          0
X7          0
X8          1
X9          0
X10         6
X11         0
X12         0
X13         0
X14         0
X15       160
X16         6
X17         0
X18         0
X19         0
X20         0
X21         1
X22         0
X23         6
X24         6
X25         6
X26         7
X27         6
X28         0
X29         0
X30         0
X31         0
X32         0
X33         0
X34         0
X35         0
X36         0
X37         0
X38         0
X39         0
X40         0
X41         0
X42        31
X43         0
X44         0
X45         0
X46         0
X47         0
X48        13
X49         0
Y           0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 51 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CoilID  1352 non-null   int64
 1   X1      1352 non-null   float64
 2   X2      1352 non-null   float64
 3   X3      1352 non-null   float64
 4   X4      1352 non-null   float64
 5   X5      1352 non-null   float64
 6   X6      1352 non-null   float64
 7   X7      1352 non-null   float64
 8   X8      1351 non-null   float64
 9   X9      1352 non-null   float64
 10  X10     1346 non-null   float64
 11  X11     1352 non-null   float64
 12  X12     1352 non-null   float64
 13  X13     1352 non-null   float64
 14  X14     1352 non-null   float64
 15  X15     1192 non-null   float64
 16  X16     1346 non-null   float64
 17  X17     1352 non-null   float64
 18  X18     1352 non-null   float64
 19  X19     1352 non-null   float64
 20  X20     1352 non-null   float64
 21  X21     1351 non-null   float64
 22  X22     1352 non-null   float64
 23  X23     1346 non-null   float64
 24  X24     1346 non-null   float64
 25  X25     1346 non-null   float64
 26  X26     1345 non-null   float64
 27  X27     1346 non-null   float64
 28  X28     1352 non-null   float64
 29  X29     1352 non-null   float64
 30  X30     1352 non-null   float64
 31  X31     1352 non-null   float64
 32  X32     1352 non-null   float64
 33  X33     1352 non-null   float64
 34  X34     1352 non-null   float64
 35  X35     1352 non-null   float64
 36  X36     1352 non-null   float64
 37  X37     1352 non-null   float64
 38  X38     1352 non-null   float64
 39  X39     1352 non-null   float64
 40  X40     1352 non-null   float64
 41  X41     1352 non-null   float64
 42  X42     1321 non-null   float64
 43  X43     1352 non-null   float64
 44  X44     1352 non-null   float64
 45  X45     1352 non-null   float64
 46  X46     1352 non-null   float64
 47  X47     1352 non-null   float64
 48  X48     1339 non-null   float64
 49  X49     1352 non-null   float64
 50  Y       1352 non-null   float64
dtypes: float64(50), int64(1)
memory usage: 538.8 KB

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1351.000000,1352.000000,...,1352.000000,1321.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1339.000000,1352.000000,1352.000000
mean,833.515533,1028.915322,575.374555,538.372787,692.576938,649.010832,618.584573,529.241056,528.770054,461.699867,...,0.585886,0.011334,0.281290,0.091495,11.507361,0.002745,0.050913,0.007108,0.064400,0.048817
std,487.420566,108.505011,232.103882,135.288085,56.798904,35.398207,45.602831,46.263179,40.220201,40.600916,...,0.296115,0.017114,0.068455,0.073058,25.004864,0.006660,0.044617,0.012504,0.050905,0.215564
min,1.000000,235.252250,96.755492,124.150450,575.916250,559.272859,529.937396,439.221384,425.413251,343.110465,...,0.077352,0.000000,0.029599,0.000000,-82.672877,0.000000,0.016833,0.000000,0.000000,0.000000
25%,411.250000,1009.279089,405.533242,441.585514,622.213663,625.327743,583.363796,476.813303,520.192858,423.604248,...,0.365881,0.000380,0.244377,0.026073,-1.368777,0.000943,0.039864,0.000000,0.015624,0.000000
50%,824.500000,1071.978233,589.160841,548.035306,724.970407,661.170690,615.240491,547.648095,545.399528,482.412285,...,0.574328,0.002613,0.293164,0.076108,9.177752,0.001644,0.045829,0.001056,0.060336,0.000000
75%,1254.250000,1092.031100,725.766924,632.238363,734.453213,668.054192,659.564239,554.584166,556.334294,488.713960,...,0.797025,0.013933,0.334613,0.143156,24.196605,0.002275,0.051435,0.002679,0.106017,0.000000
max,1691.000000,1124.903234,1148.171484,1026.915778,755.983296,763.257466,742.725523,618.947910,575.312130,505.349388,...,1.377925,0.062637,0.409739,0.329108,120.169658,0.064545,0.424405,0.051150,0.249522,1.000000

In [5]:
# Separating the features and the target variable 'Y'

X_hot_rolling = hot_rolling_df.drop(columns=['CoilID', 'Y'])
Y_hot_rolling = hot_rolling_df['Y']

In [6]:
# Handling the missing values using the Imputer (KNNImputer)

imputer = KNNImputer(n_neighbors=5)
X_hot_rolling_imputed = imputer.fit_transform(X_hot_rolling)
# converting it to the dataframe
X_hot_rolling_imputed = pd.DataFrame(X_hot_rolling_imputed, columns=X_hot_rolling.columns)


# checking the missing values after imputation
print("Missing values after imputation: ")
print(X_hot_rolling_imputed.isnull().sum())
print("Shape of the imputed dataset: ", X_hot_rolling_imputed.shape)

hot_rolling_df.info()
hot_rolling_df.describe()

Missing values after imputation:
X1     0
X2     0
X3     0
X4     0
X5     0
X6     0
X7     0
X8     0
X9     0
X10    0
X11    0
X12    0
X13    0
X14    0
X15    0
X16    0
X17    0
X18    0
X19    0
X20    0
X21    0
X22    0
X23    0
X24    0
X25    0
X26    0
X27    0
X28    0
X29    0
X30    0
X31    0
X32    0
X33    0
X34    0
X35    0
X36    0
X37    0
X38    0
X39    0
X40    0
X41    0
X42    0
X43    0
X44    0
X45    0
X46    0
X47    0
X48    0
X49    0
dtype: int64
Shape of the imputed dataset:  (1352, 49)
<class 'pandas.DataFrame'>
RangeIndex: 1352 entries, 0 to 1351
Data columns (total 51 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CoilID  1352 non-null   int64
 1   X1      1352 non-null   float64
 2   X2      1352 non-null   float64
 3   X3      1352 non-null   float64
 4   X4      1352 non-null   float64
 5   X5      1352 non-null   float64
 6   X6      1352 non-null   float64
 7   X7      1352 non-null   float64
 8   X8      1351 non-null   float64
 9   X9      1352 non-null   float64
 10  X10     1346 non-null   float64
 11  X11     1352 non-null   float64
 12  X12     1352 non-null   float64
 13  X13     1352 non-null   float64
 14  X14     1352 non-null   float64
 15  X15     1192 non-null   float64
 16  X16     1346 non-null   float64
 17  X17     1352 non-null   float64
 18  X18     1352 non-null   float64
 19  X19     1352 non-null   float64
 20  X20     1352 non-null   float64
 21  X21     1351 non-null   float64
 22  X22     1352 non-null   float64
 23  X23     1346 non-null   float64
 24  X24     1346 non-null   float64
 25  X25     1346 non-null   float64
 26  X26     1345 non-null   float64
 27  X27     1346 non-null   float64
 28  X28     1352 non-null   float64
 29  X29     1352 non-null   float64
 30  X30     1352 non-null   float64
 31  X31     1352 non-null   float64
 32  X32     1352 non-null   float64
 33  X33     1352 non-null   float64
 34  X34     1352 non-null   float64
 35  X35     1352 non-null   float64
 36  X36     1352 non-null   float64
 37  X37     1352 non-null   float64
 38  X38     1352 non-null   float64
 39  X39     1352 non-null   float64
 40  X40     1352 non-null   float64
 41  X41     1352 non-null   float64
 42  X42     1321 non-null   float64
 43  X43     1352 non-null   float64
 44  X44     1352 non-null   float64
 45  X45     1352 non-null   float64
 46  X46     1352 non-null   float64
 47  X47     1352 non-null   float64
 48  X48     1339 non-null   float64
 49  X49     1352 non-null   float64
 50  Y       1352 non-null   float64
dtypes: float64(50), int64(1)
memory usage: 538.8 KB

,CoilID,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X41,X42,X43,X44,X45,X46,X47,X48,X49,Y
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1351.000000,1352.000000,...,1352.000000,1321.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1339.000000,1352.000000,1352.000000
mean,833.515533,1028.915322,575.374555,538.372787,692.576938,649.010832,618.584573,529.241056,528.770054,461.699867,...,0.585886,0.011334,0.281290,0.091495,11.507361,0.002745,0.050913,0.007108,0.064400,0.048817
std,487.420566,108.505011,232.103882,135.288085,56.798904,35.398207,45.602831,46.263179,40.220201,40.600916,...,0.296115,0.017114,0.068455,0.073058,25.004864,0.006660,0.044617,0.012504,0.050905,0.215564
min,1.000000,235.252250,96.755492,124.150450,575.916250,559.272859,529.937396,439.221384,425.413251,343.110465,...,0.077352,0.000000,0.029599,0.000000,-82.672877,0.000000,0.016833,0.000000,0.000000,0.000000
25%,411.250000,1009.279089,405.533242,441.585514,622.213663,625.327743,583.363796,476.813303,520.192858,423.604248,...,0.365881,0.000380,0.244377,0.026073,-1.368777,0.000943,0.039864,0.000000,0.015624,0.000000
50%,824.500000,1071.978233,589.160841,548.035306,724.970407,661.170690,615.240491,547.648095,545.399528,482.412285,...,0.574328,0.002613,0.293164,0.076108,9.177752,0.001644,0.045829,0.001056,0.060336,0.000000
75%,1254.250000,1092.031100,725.766924,632.238363,734.453213,668.054192,659.564239,554.584166,556.334294,488.713960,...,0.797025,0.013933,0.334613,0.143156,24.196605,0.002275,0.051435,0.002679,0.106017,0.000000
max,1691.000000,1124.903234,1148.171484,1026.915778,755.983296,763.257466,742.725523,618.947910,575.312130,505.349388,...,1.377925,0.062637,0.409739,0.329108,120.169658,0.064545,0.424405,0.051150,0.249522,1.000000

In [7]:
# Feature Scaling or Normalization of the dataset

scaler = StandardScaler()
X_hot_rolling_scaled = scaler.fit_transform(X_hot_rolling_imputed)

In [8]:
# Feature Scaling 

from sklearn.feature_selection import SelectFromModel, mutual_info_classif

mi_scores_hot_rolling = mutual_info_classif(X_hot_rolling_scaled, Y_hot_rolling, random_state=42)
mi_series_hot_rolling = pd.Series(mi_scores_hot_rolling, index=X_hot_rolling.columns).sort_values(ascending=False)

print("Top 10 features based on the Mutual Information Scores: \n", mi_series_hot_rolling.head(10))

Top 10 features based on the Mutual Information Scores:
 X36    0.039463
X13    0.038971
X34    0.033676
X32    0.033534
X39    0.030829
X10    0.028052
X30    0.027061
X6     0.026641
X35    0.026247
X33    0.024256
dtype: float64

In [9]:
# Selecting the top 20 features 

top_20_features_hot_rolling = mi_series_hot_rolling.head(20).index.tolist()

X_hot_rolling_selected = X_hot_rolling_imputed[top_20_features_hot_rolling]

print("shape of the dataset after the feature selection: ", X_hot_rolling_selected.shape)

X_hot_rolling_selected.describe()

shape of the dataset after the feature selection:  (1352, 20)

,X36,X13,X34,X32,X39,X10,X30,X6,X35,X33,X31,X28,X18,X15,X38,X29,X37,X5,X41,X24
count,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1.352000e+03,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000,1352.000000
mean,2279.289201,868.915869,2359.427515,15.998457,162.281065,6.861327,10.095567,618.584573,9.922451e+06,17.119898,13.506972,4.749715,890.539824,3.446813,690.497041,6.948415,1641.233728,649.010832,0.585886,16.349268
std,1767.389750,397.296095,1770.224468,3.784762,11.368766,2.631377,2.250786,45.602831,6.665497e+06,3.670994,3.259872,0.602077,7.991223,2.172425,1263.545639,1.093988,1741.161108,35.398207,0.296115,4.990185
min,0.000000,97.078178,0.000000,6.508389,98.000000,1.117275,4.356228,529.937396,0.000000e+00,6.714073,5.880277,4.321103,858.748809,1.173575,0.000000,4.578510,0.000000,559.272859,0.077352,-1.262651
25%,98.750000,545.825307,90.000000,13.470451,160.000000,4.702552,8.769181,583.363796,4.627258e+05,14.923421,11.121122,4.482384,887.174583,2.005021,0.000000,6.234717,45.000000,625.327743,0.365881,14.711926
50%,3559.500000,842.055177,3487.000000,16.295053,164.000000,6.983717,10.119274,615.240491,1.394034e+07,19.046641,13.846186,4.543375,890.031317,2.776068,74.500000,6.912886,553.000000,661.170690,0.574328,16.942795
75%,3865.250000,1169.875976,3861.250000,19.721242,169.000000,8.940686,11.774199,659.564239,1.488926e+07,19.977972,15.900814,4.646584,896.489977,4.089900,613.750000,7.834167,3756.250000,668.054192,0.797025,19.368358
max,4296.000000,1631.918408,4380.000000,24.508596,173.000000,12.312371,14.913641,742.725523,1.774067e+07,25.232161,20.290997,6.635675,918.084739,12.327319,4155.000000,10.253523,4457.000000,763.257466,1.377925,30.789863

In [10]:
# Adressing the class imbalance using SMOTE

stratified_shuffled_split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_indx, test_indx in stratified_shuffled_split.split(X_hot_rolling_selected, Y_hot_rolling):
    
    X_train_hot_rolling, X_test_hot_rolling = X_hot_rolling_selected.iloc[train_indx], X_hot_rolling_selected.iloc[test_indx]
    y_train_hot_rolling, y_test_hot_rolling = Y_hot_rolling[train_indx], Y_hot_rolling[test_indx]
    

print(f"Train defect ratio : {y_train_hot_rolling.mean():.4f}")
print(f"Test defect ratio : {y_test_hot_rolling.mean():.4f}")

# Applying SMOTE to the training data

smote = SMOTE(random_state=42, sampling_strategy=0.3)
X_train_hot_rolling_smote, y_train_hot_rolling_smote = smote.fit_resample(X_train_hot_rolling, y_train_hot_rolling)

print(f"Shape of training data after SMOTE: {X_train_hot_rolling_smote.shape}")
print(f"Defect ratio of training data after SMOTE: {y_train_hot_rolling_smote.mean():.4f}")

Train defect ratio : 0.0490
Test defect ratio : 0.0480
Shape of training data after SMOTE: (1336, 20)
Defect ratio of training data after SMOTE: 0.2305

### Model Preparation

In [11]:
# calculating scale_pos_weight as the ratio of the negative to positive samples

from sklearn.metrics import recall_score, precision_score, f1_score, roc_auc_score, precision_recall_curve, confusion_matrix

scale_pos_weight = (y_train_hot_rolling == 0).sum() / (y_train_hot_rolling == 1).sum()
print(f"Scale pos weight : {scale_pos_weight:.4f}")


xgb_classifier = xgb.XGBClassifier(
    scale_pos_weight = scale_pos_weight,
    eval_metric = 'logloss',
    random_state = 42,
    use_label_encoder = False
)

xgb_classifier.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Evaluating on the test set
y_pred_xgb = xgb_classifier.predict(X_test_hot_rolling)

print("Baseline XGBoost Classifier Performance : ")
print(f"Recall : {recall_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"Precision : {precision_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"F1 Score : {f1_score(y_test_hot_rolling, y_pred_xgb):.4f}")
print(f"ROC AUC Score : {roc_auc_score(y_test_hot_rolling, y_pred_xgb):.4f}")

Scale pos weight : 19.3962
Baseline XGBoost Classifier Performance :
Recall : 0.4615
Precision : 0.2609
F1 Score : 0.3333
ROC AUC Score : 0.6978

In [18]:
## Hyperparameter Tuning using GridSearchCV

import optuna
from sklearn.model_selection import GridSearchCV, cross_val_predict

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 300, 800, step=50),
        'max_depth': trial.suggest_int('max_depth', 4, 8),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'subsample': trial.suggest_float('subsample', 0.6, 0.9),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 0.9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 0.5),
        'reg_alpha': trial.suggest_float('reg_alpha', 0, 0.1),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.5, 2.0),
        'scale_pos_weight': trial.suggest_int('scale_pos_weight', 50, 150),
        'eval_metric': 'logloss',
        'random_state': 42,
        'use_label_encoder': False
    }
    
    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
    recall_scores = []
    precision_scores = []
    
    for train_indx, val_indx in skf.split(X_train_hot_rolling_smote, y_train_hot_rolling_smote):
        X_train_fold, X_val_fold = X_train_hot_rolling_smote.iloc[train_indx], X_train_hot_rolling_smote.iloc[val_indx]
        y_train_fold, y_val_fold = y_train_hot_rolling_smote.iloc[train_indx], y_train_hot_rolling_smote.iloc[val_indx]
        
        model = xgb.XGBClassifier(**params)
        model.fit(X_train_fold, y_train_fold)
        
        y_val_pred = model.predict(X_val_fold)
        recall_scores.append(recall_score(y_val_fold, y_val_pred))
        precision_scores.append(precision_score(y_val_fold, y_val_pred))
        
        # using f2 score as the optimization metric to give more weight to recall
        
        f2_scores = (5 * np.mean(recall_scores) * np.mean(precision_scores)) / (4 * np.mean(precision_scores) + np.mean(recall_scores) + 1e-8)
        
        return f2_scores

In [16]:
%pip install --upgrade xgboost

Requirement already satisfied: xgboost in ./.venv/lib/python3.14/site-packages (3.2.0)
Requirement already satisfied: numpy in ./.venv/lib/python3.14/site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in ./.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50, show_progress_bar=True)
best_params = study.best_params
print("Best Hyperparameters : ", best_params)

# Training final XGBoost model with the best hyperparameters
xgb_final_classifier = xgb.XGBClassifier(**best_params, use_label_encoder=False)
xgb_final_classifier.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Cross validation with best model (Stratified K-Fold)


skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_recall = []
cv_precision = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_train_hot_rolling_smote, y_train_hot_rolling_smote)):
    X_train_fold, X_val_fold = X_train_hot_rolling_smote.iloc[train_idx], X_train_hot_rolling_smote.iloc[val_idx]
    y_train_fold, y_val_fold = y_train_hot_rolling_smote.iloc[train_idx], y_train_hot_rolling_smote.iloc[val_idx]
    
    model = xgb.XGBClassifier(**best_params, use_label_encoder=False)
    model.fit(X_train_fold, y_train_fold)
    
    y_pred = model.predict(X_val_fold)
    cv_recall.append(recall_score(y_val_fold, y_pred))
    cv_precision.append(precision_score(y_val_fold, y_pred))
    
    print(f"Fold {fold+1} -  Recall: {cv_recall[-1]:.4f}, Precision: {cv_precision[-1]:.4f}")
    
print(f"CV Average Recall: {np.mean(cv_recall):.4f} (+/- {np.std(cv_recall):.4f})")
print(f"CV Average Precision: {np.mean(cv_precision):.4f} (+/- {np.std(cv_precision):.4f})")

[I 2026-05-30 12:01:19,464] A new study created in memory with name: no-name-8de8a06b-3c6f-4236-a119-392c496d2dab
Best trial: 0. Best value: 0.877514:   2%|▏         | 1/50 [00:00<00:37,  1.31it/s]

[I 2026-05-30 12:01:20,243] Trial 0 finished with value: 0.8775137088281101 and parameters: {'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.014053644271647486, 'subsample': 0.6553807371764759, 'colsample_bytree': 0.66886771150264, 'min_child_weight': 4, 'gamma': 0.2785516268213261, 'reg_alpha': 0.013084773888773493, 'reg_lambda': 0.9792780534454306, 'scale_pos_weight': 124}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:   4%|▍         | 2/50 [00:01<00:45,  1.07it/s]

[I 2026-05-30 12:01:21,304] Trial 1 finished with value: 0.8955223858369067 and parameters: {'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.016243171194057014, 'subsample': 0.8719710747029713, 'colsample_bytree': 0.7320260525935436, 'min_child_weight': 4, 'gamma': 0.1666312612079625, 'reg_alpha': 0.09753470593281734, 'reg_lambda': 1.2564033624807742, 'scale_pos_weight': 112}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:   6%|▌         | 3/50 [00:02<00:36,  1.28it/s]

[I 2026-05-30 12:01:21,900] Trial 2 finished with value: 0.8818011235100621 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.028776913903690197, 'subsample': 0.8079131455255899, 'colsample_bytree': 0.6790631297557519, 'min_child_weight': 3, 'gamma': 0.48557516347511903, 'reg_alpha': 0.07045439760890114, 'reg_lambda': 1.861524407122091, 'scale_pos_weight': 75}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:   8%|▊         | 4/50 [00:03<00:36,  1.27it/s]

[I 2026-05-30 12:01:22,692] Trial 3 finished with value: 0.8921933063083014 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.01274772743920316, 'subsample': 0.850568224498923, 'colsample_bytree': 0.8311128485890831, 'min_child_weight': 2, 'gamma': 0.478486919041978, 'reg_alpha': 0.029114435672434547, 'reg_lambda': 1.6337198205545018, 'scale_pos_weight': 88}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:  10%|█         | 5/50 [00:03<00:32,  1.37it/s]

[I 2026-05-30 12:01:23,323] Trial 4 finished with value: 0.8971962594691238 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.03291689560423291, 'subsample': 0.8109996757705602, 'colsample_bytree': 0.6902683776235674, 'min_child_weight': 8, 'gamma': 0.10323752310750112, 'reg_alpha': 0.061626471807244336, 'reg_lambda': 1.2151852135107846, 'scale_pos_weight': 93}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:  12%|█▏        | 6/50 [00:04<00:26,  1.65it/s]

[I 2026-05-30 12:01:23,692] Trial 5 finished with value: 0.8895131064108768 and parameters: {'n_estimators': 450, 'max_depth': 7, 'learning_rate': 0.096533586954007, 'subsample': 0.8908968712340093, 'colsample_bytree': 0.739603392046831, 'min_child_weight': 8, 'gamma': 0.13783803215842677, 'reg_alpha': 0.01171533579718419, 'reg_lambda': 1.9704133510102781, 'scale_pos_weight': 77}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:  14%|█▍        | 7/50 [00:04<00:24,  1.79it/s]

[I 2026-05-30 12:01:24,152] Trial 6 finished with value: 0.8823529388793522 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.040086230350535206, 'subsample': 0.6080710329687232, 'colsample_bytree': 0.6229370741017017, 'min_child_weight': 8, 'gamma': 0.18574850317250619, 'reg_alpha': 0.07409457527056523, 'reg_lambda': 0.8097081338752317, 'scale_pos_weight': 111}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 0. Best value: 0.877514:  16%|█▌        | 8/50 [00:05<00:22,  1.87it/s]

[I 2026-05-30 12:01:24,636] Trial 7 finished with value: 0.8823529390439961 and parameters: {'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.08430129486803824, 'subsample': 0.8479735220504816, 'colsample_bytree': 0.7285548599045449, 'min_child_weight': 3, 'gamma': 0.025133677044752556, 'reg_alpha': 0.062245444931974064, 'reg_lambda': 1.8539247020259073, 'scale_pos_weight': 116}. Best is trial 0 with value: 0.8775137088281101.

Best trial: 8. Best value: 0.872727:  18%|█▊        | 9/50 [00:05<00:23,  1.73it/s]

[I 2026-05-30 12:01:25,305] Trial 8 finished with value: 0.8727272703778512 and parameters: {'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.015600177048902071, 'subsample': 0.6545726832402158, 'colsample_bytree': 0.745174580839175, 'min_child_weight': 10, 'gamma': 0.1527227315155409, 'reg_alpha': 0.050514028372842405, 'reg_lambda': 1.330780284929516, 'scale_pos_weight': 68}. Best is trial 8 with value: 0.8727272703778512.

Best trial: 8. Best value: 0.872727:  20%|██        | 10/50 [00:06<00:23,  1.70it/s]

[I 2026-05-30 12:01:25,919] Trial 9 finished with value: 0.8867924506667855 and parameters: {'n_estimators': 750, 'max_depth': 8, 'learning_rate': 0.049786416907872694, 'subsample': 0.7596508658972253, 'colsample_bytree': 0.8209170215226713, 'min_child_weight': 5, 'gamma': 0.46426852208738456, 'reg_alpha': 0.0313029266197554, 'reg_lambda': 0.7732277893242346, 'scale_pos_weight': 66}. Best is trial 8 with value: 0.8727272703778512.

Best trial: 8. Best value: 0.872727:  22%|██▏       | 11/50 [00:06<00:18,  2.06it/s]

[I 2026-05-30 12:01:26,172] Trial 10 finished with value: 0.8869565192001513 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.02118712711884479, 'subsample': 0.7029463691072843, 'colsample_bytree': 0.8954343861610304, 'min_child_weight': 10, 'gamma': 0.2743575196339992, 'reg_alpha': 0.03800000553001244, 'reg_lambda': 1.465742140566146, 'scale_pos_weight': 146}. Best is trial 8 with value: 0.8727272703778512.

Best trial: 8. Best value: 0.872727:  24%|██▍       | 12/50 [00:07<00:21,  1.80it/s]

[I 2026-05-30 12:01:26,884] Trial 11 finished with value: 0.8892921936493953 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.010062799703939088, 'subsample': 0.6413086351441546, 'colsample_bytree': 0.6063876197242755, 'min_child_weight': 6, 'gamma': 0.3250545294803957, 'reg_alpha': 0.0009300948944211893, 'reg_lambda': 1.0279056869896261, 'scale_pos_weight': 50}. Best is trial 8 with value: 0.8727272703778512.

Best trial: 8. Best value: 0.872727:  26%|██▌       | 13/50 [00:08<00:24,  1.51it/s]

[I 2026-05-30 12:01:27,792] Trial 12 finished with value: 0.9022556369141839 and parameters: {'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.019490878436109797, 'subsample': 0.6889839208907046, 'colsample_bytree': 0.7957689655539805, 'min_child_weight': 1, 'gamma': 0.3535820583401287, 'reg_alpha': 0.04597058504451622, 'reg_lambda': 1.0265972913190466, 'scale_pos_weight': 135}. Best is trial 8 with value: 0.8727272703778512.

Best trial: 13. Best value: 0.866071:  28%|██▊       | 14/50 [00:08<00:23,  1.55it/s]

[I 2026-05-30 12:01:28,394] Trial 13 finished with value: 0.8660714261409439 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.013378066195311284, 'subsample': 0.6792193239013558, 'colsample_bytree': 0.6594965015091786, 'min_child_weight': 10, 'gamma': 0.23225084207932764, 'reg_alpha': 0.01091482420282261, 'reg_lambda': 0.5183357794005024, 'scale_pos_weight': 130}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  30%|███       | 15/50 [00:09<00:22,  1.54it/s]

[I 2026-05-30 12:01:29,050] Trial 14 finished with value: 0.8679927643524226 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.010904477679807565, 'subsample': 0.7279220638005351, 'colsample_bytree': 0.7741383283416106, 'min_child_weight': 10, 'gamma': 0.05494358164024796, 'reg_alpha': 0.08553501639159738, 'reg_lambda': 1.4584681424610073, 'scale_pos_weight': 50}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  32%|███▏      | 16/50 [00:10<00:21,  1.59it/s]

[I 2026-05-30 12:01:29,640] Trial 15 finished with value: 0.8818342126845709 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.010513649962860494, 'subsample': 0.7406515970429597, 'colsample_bytree': 0.7830865025341774, 'min_child_weight': 9, 'gamma': 0.004919434048899905, 'reg_alpha': 0.09917906040947522, 'reg_lambda': 0.5516146965735125, 'scale_pos_weight': 148}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  34%|███▍      | 17/50 [00:10<00:20,  1.59it/s]

[I 2026-05-30 12:01:30,268] Trial 16 finished with value: 0.8780036945877936 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.022657540751032507, 'subsample': 0.7402676896033841, 'colsample_bytree': 0.644481253369307, 'min_child_weight': 7, 'gamma': 0.06729127665916451, 'reg_alpha': 0.0852300890208298, 'reg_lambda': 1.5677255290986143, 'scale_pos_weight': 55}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  36%|███▌      | 18/50 [00:11<00:19,  1.60it/s]

[I 2026-05-30 12:01:30,882] Trial 17 finished with value: 0.8812615932960096 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.05756727158642473, 'subsample': 0.7050300312838623, 'colsample_bytree': 0.8756484631791139, 'min_child_weight': 10, 'gamma': 0.2203856575557087, 'reg_alpha': 0.08613240669974837, 'reg_lambda': 0.5074834605410917, 'scale_pos_weight': 101}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  38%|███▊      | 19/50 [00:11<00:16,  1.83it/s]

[I 2026-05-30 12:01:31,247] Trial 18 finished with value: 0.8762886572091143 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.012572919419147762, 'subsample': 0.7693882481541576, 'colsample_bytree': 0.7698417574655801, 'min_child_weight': 9, 'gamma': 0.41737099881293205, 'reg_alpha': 0.017843736953686944, 'reg_lambda': 1.657188739800729, 'scale_pos_weight': 134}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 13. Best value: 0.866071:  40%|████      | 20/50 [00:12<00:16,  1.81it/s]

[I 2026-05-30 12:01:31,816] Trial 19 finished with value: 0.8752327724417328 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.02846599560299614, 'subsample': 0.6025865194030573, 'colsample_bytree': 0.7037068762718374, 'min_child_weight': 6, 'gamma': 0.06829730363777305, 'reg_alpha': 0.05050526658402221, 'reg_lambda': 0.7101282687213247, 'scale_pos_weight': 101}. Best is trial 13 with value: 0.8660714261409439.

Best trial: 20. Best value: 0.864865:  42%|████▏     | 21/50 [00:12<00:16,  1.76it/s]

[I 2026-05-30 12:01:32,423] Trial 20 finished with value: 0.8648648624739875 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.01693985552112756, 'subsample': 0.6803746333658977, 'colsample_bytree': 0.8421917343839622, 'min_child_weight': 9, 'gamma': 0.3592055106387372, 'reg_alpha': 0.0006130232951274822, 'reg_lambda': 1.4150129454362894, 'scale_pos_weight': 133}. Best is trial 20 with value: 0.8648648624739875.

Best trial: 20. Best value: 0.864865:  44%|████▍     | 22/50 [00:13<00:16,  1.72it/s]

[I 2026-05-30 12:01:33,034] Trial 21 finished with value: 0.8695652150250734 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.017647573926252113, 'subsample': 0.6824312692991871, 'colsample_bytree': 0.8447591598805889, 'min_child_weight': 9, 'gamma': 0.3764226610201187, 'reg_alpha': 0.0006124329432112034, 'reg_lambda': 1.424900854096619, 'scale_pos_weight': 131}. Best is trial 20 with value: 0.8648648624739875.

Best trial: 22. Best value: 0.864528:  46%|████▌     | 23/50 [00:14<00:16,  1.59it/s]

[I 2026-05-30 12:01:33,773] Trial 22 finished with value: 0.8645276267953204 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.011884990791074808, 'subsample': 0.7114365643728696, 'colsample_bytree': 0.8558388814317627, 'min_child_weight': 10, 'gamma': 0.3151034296623495, 'reg_alpha': 0.022643887815158276, 'reg_lambda': 1.1655203960911897, 'scale_pos_weight': 123}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  48%|████▊     | 24/50 [00:14<00:15,  1.63it/s]

[I 2026-05-30 12:01:34,348] Trial 23 finished with value: 0.8699633676484994 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.024707363449239867, 'subsample': 0.6717193603840594, 'colsample_bytree': 0.8606357649461329, 'min_child_weight': 7, 'gamma': 0.3168946220261146, 'reg_alpha': 0.0249702544841678, 'reg_lambda': 1.1490411721707958, 'scale_pos_weight': 123}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  50%|█████     | 25/50 [00:15<00:14,  1.72it/s]

[I 2026-05-30 12:01:34,860] Trial 24 finished with value: 0.8849557497440677 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.013562656442918087, 'subsample': 0.6282901531504673, 'colsample_bytree': 0.8111310055543587, 'min_child_weight': 9, 'gamma': 0.22167192670502137, 'reg_alpha': 0.009406817000222657, 'reg_lambda': 1.102756968326834, 'scale_pos_weight': 140}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  52%|█████▏    | 26/50 [00:15<00:13,  1.73it/s]

[I 2026-05-30 12:01:35,428] Trial 25 finished with value: 0.8802177834860557 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.017671573156740613, 'subsample': 0.7131559280998425, 'colsample_bytree': 0.8952256505863347, 'min_child_weight': 7, 'gamma': 0.40946040687346336, 'reg_alpha': 0.021667254250858456, 'reg_lambda': 0.8905120440686554, 'scale_pos_weight': 125}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  54%|█████▍    | 27/50 [00:16<00:14,  1.57it/s]

[I 2026-05-30 12:01:36,196] Trial 26 finished with value: 0.8691756248252849 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.011926803651122296, 'subsample': 0.785421009241949, 'colsample_bytree': 0.8608366827536843, 'min_child_weight': 10, 'gamma': 0.3077063495406776, 'reg_alpha': 0.0055116495041558486, 'reg_lambda': 1.3262682537946233, 'scale_pos_weight': 141}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  56%|█████▌    | 28/50 [00:17<00:13,  1.58it/s]

[I 2026-05-30 12:01:36,823] Trial 27 finished with value: 0.8818181794687604 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.0160107489154045, 'subsample': 0.6673521739304834, 'colsample_bytree': 0.6531026825627994, 'min_child_weight': 8, 'gamma': 0.24471103371984593, 'reg_alpha': 0.03599957487373823, 'reg_lambda': 0.6510649841338263, 'scale_pos_weight': 119}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  58%|█████▊    | 29/50 [00:17<00:12,  1.72it/s]

[I 2026-05-30 12:01:37,289] Trial 28 finished with value: 0.8849557497440677 and parameters: {'n_estimators': 450, 'max_depth': 5, 'learning_rate': 0.014072224831071713, 'subsample': 0.7256992250429232, 'colsample_bytree': 0.8436145763450664, 'min_child_weight': 9, 'gamma': 0.36376827520137067, 'reg_alpha': 0.013267351452702292, 'reg_lambda': 1.7173662845405473, 'scale_pos_weight': 107}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  60%|██████    | 30/50 [00:18<00:11,  1.68it/s]

[I 2026-05-30 12:01:37,908] Trial 29 finished with value: 0.8695652150250734 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.019215638563253184, 'subsample': 0.6458034253895106, 'colsample_bytree': 0.7995862008187774, 'min_child_weight': 10, 'gamma': 0.2763459591995826, 'reg_alpha': 0.018143860849403236, 'reg_lambda': 0.9631063580110178, 'scale_pos_weight': 128}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  62%|██████▏   | 31/50 [00:19<00:11,  1.60it/s]

[I 2026-05-30 12:01:38,609] Trial 30 finished with value: 0.8786231860395664 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.014531431852576049, 'subsample': 0.6929698799645718, 'colsample_bytree': 0.7084195579487427, 'min_child_weight': 9, 'gamma': 0.4226840362843289, 'reg_alpha': 0.007819042152877115, 'reg_lambda': 0.6028976169234274, 'scale_pos_weight': 141}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  64%|██████▍   | 32/50 [00:19<00:11,  1.57it/s]

[I 2026-05-30 12:01:39,266] Trial 31 finished with value: 0.8849557497440677 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.010888275523047674, 'subsample': 0.7215446062384185, 'colsample_bytree': 0.7793639535126452, 'min_child_weight': 10, 'gamma': 0.3388901312850323, 'reg_alpha': 0.015904629024794708, 'reg_lambda': 1.483412669602625, 'scale_pos_weight': 123}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  66%|██████▌   | 33/50 [00:20<00:10,  1.60it/s]

[I 2026-05-30 12:01:39,872] Trial 32 finished with value: 0.8734402827668 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.011532100016268448, 'subsample': 0.7284862412444472, 'colsample_bytree': 0.7622499981481703, 'min_child_weight': 10, 'gamma': 0.396012698168398, 'reg_alpha': 0.005369035179757919, 'reg_lambda': 1.3625496156734649, 'scale_pos_weight': 87}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  68%|██████▊   | 34/50 [00:20<00:09,  1.64it/s]

[I 2026-05-30 12:01:40,438] Trial 33 finished with value: 0.8963093120896279 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.010052712176415277, 'subsample': 0.6728624885483631, 'colsample_bytree': 0.8732750083131143, 'min_child_weight': 9, 'gamma': 0.2952730188298274, 'reg_alpha': 0.09095169239658457, 'reg_lambda': 1.2302339985662902, 'scale_pos_weight': 115}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  70%|███████   | 35/50 [00:21<00:09,  1.53it/s]

[I 2026-05-30 12:01:41,202] Trial 34 finished with value: 0.8711433733227163 and parameters: {'n_estimators': 750, 'max_depth': 5, 'learning_rate': 0.012746703409658196, 'subsample': 0.7782134897739131, 'colsample_bytree': 0.8358237124810712, 'min_child_weight': 8, 'gamma': 0.20548286851579695, 'reg_alpha': 0.023708911362559662, 'reg_lambda': 1.7282842123781903, 'scale_pos_weight': 108}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  72%|███████▏  | 36/50 [00:22<00:09,  1.49it/s]

[I 2026-05-30 12:01:41,918] Trial 35 finished with value: 0.8797127444512312 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.014987592459730501, 'subsample': 0.7478088693341807, 'colsample_bytree': 0.6661804915633409, 'min_child_weight': 10, 'gamma': 0.2531397841956356, 'reg_alpha': 0.07224324130916535, 'reg_lambda': 1.4788561476903737, 'scale_pos_weight': 133}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  74%|███████▍  | 37/50 [00:22<00:08,  1.60it/s]

[I 2026-05-30 12:01:42,430] Trial 36 finished with value: 0.8792184700155221 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.01180105062251327, 'subsample': 0.7972770426622511, 'colsample_bytree': 0.7229355794756657, 'min_child_weight': 5, 'gamma': 0.44691199644617025, 'reg_alpha': 0.04058513415170069, 'reg_lambda': 1.5585923302652895, 'scale_pos_weight': 150}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  76%|███████▌  | 38/50 [00:23<00:07,  1.69it/s]

[I 2026-05-30 12:01:42,941] Trial 37 finished with value: 0.8797127444512312 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.016637784190068235, 'subsample': 0.7006954399240185, 'colsample_bytree': 0.8146751155575268, 'min_child_weight': 8, 'gamma': 0.12838946037149607, 'reg_alpha': 0.06348081595632282, 'reg_lambda': 1.1312424915011663, 'scale_pos_weight': 92}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  78%|███████▊  | 39/50 [00:24<00:06,  1.68it/s]

[I 2026-05-30 12:01:43,547] Trial 38 finished with value: 0.8971962594691238 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.03559702476970012, 'subsample': 0.6202607308549166, 'colsample_bytree': 0.6854821041352358, 'min_child_weight': 9, 'gamma': 0.09905165622757847, 'reg_alpha': 0.029948011242912305, 'reg_lambda': 1.81214249983013, 'scale_pos_weight': 84}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  80%|████████  | 40/50 [00:24<00:06,  1.54it/s]

[I 2026-05-30 12:01:44,329] Trial 39 finished with value: 0.8796296273689987 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.024234824810019703, 'subsample': 0.6637409454514158, 'colsample_bytree': 0.8545680390493247, 'min_child_weight': 4, 'gamma': 0.17713749113304877, 'reg_alpha': 0.013188121504308562, 'reg_lambda': 1.9722693650466683, 'scale_pos_weight': 119}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  82%|████████▏ | 41/50 [00:25<00:05,  1.51it/s]

[I 2026-05-30 12:01:45,017] Trial 40 finished with value: 0.8759124064268208 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.014111395855398496, 'subsample': 0.6802360404991743, 'colsample_bytree': 0.7576905842547305, 'min_child_weight': 8, 'gamma': 0.3817058724348664, 'reg_alpha': 0.05780877775768596, 'reg_lambda': 1.2519373837445809, 'scale_pos_weight': 76}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  84%|████████▍ | 42/50 [00:26<00:05,  1.45it/s]

[I 2026-05-30 12:01:45,771] Trial 41 finished with value: 0.8839285689980868 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.011777269686022416, 'subsample': 0.8296589639854547, 'colsample_bytree': 0.8742090313510468, 'min_child_weight': 10, 'gamma': 0.3225733875359309, 'reg_alpha': 0.0038991684644541194, 'reg_lambda': 1.3757421876677915, 'scale_pos_weight': 141}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  86%|████████▌ | 43/50 [00:27<00:05,  1.40it/s]

[I 2026-05-30 12:01:46,543] Trial 42 finished with value: 0.8723021558744373 and parameters: {'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.01301986444624876, 'subsample': 0.7830544000182335, 'colsample_bytree': 0.8305741964937889, 'min_child_weight': 10, 'gamma': 0.3015781696248981, 'reg_alpha': 0.00728895327258523, 'reg_lambda': 1.2758874103822953, 'scale_pos_weight': 143}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  88%|████████▊ | 44/50 [00:27<00:04,  1.37it/s]

[I 2026-05-30 12:01:47,302] Trial 43 finished with value: 0.8718861185506137 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.011017961471899538, 'subsample': 0.7572235774946142, 'colsample_bytree': 0.8567760486536989, 'min_child_weight': 10, 'gamma': 0.24802132500264892, 'reg_alpha': 8.75155008293767e-05, 'reg_lambda': 1.5216240637889373, 'scale_pos_weight': 136}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  90%|█████████ | 45/50 [00:28<00:03,  1.42it/s]

[I 2026-05-30 12:01:47,954] Trial 44 finished with value: 0.8718861185506137 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.01222126596983084, 'subsample': 0.7159658709707383, 'colsample_bytree': 0.89806934386857, 'min_child_weight': 9, 'gamma': 0.3515948608286021, 'reg_alpha': 0.07723122747232755, 'reg_lambda': 1.3133080439146452, 'scale_pos_weight': 126}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  92%|█████████▏| 46/50 [00:29<00:02,  1.49it/s]

[I 2026-05-30 12:01:48,545] Trial 45 finished with value: 0.8850364940180617 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.01957332019406863, 'subsample': 0.8218434363650856, 'colsample_bytree': 0.7982831379954441, 'min_child_weight': 10, 'gamma': 0.2934458533884241, 'reg_alpha': 0.011342989584077388, 'reg_lambda': 1.1891022849974235, 'scale_pos_weight': 130}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  94%|█████████▍| 47/50 [00:29<00:02,  1.46it/s]

[I 2026-05-30 12:01:49,257] Trial 46 finished with value: 0.8866544766526074 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.01567559593900252, 'subsample': 0.7950001461291555, 'colsample_bytree': 0.6267129759896317, 'min_child_weight': 10, 'gamma': 0.3393672182033707, 'reg_alpha': 0.004315482244673223, 'reg_lambda': 1.4108083543947563, 'scale_pos_weight': 65}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  96%|█████████▌| 48/50 [00:30<00:01,  1.46it/s]

[I 2026-05-30 12:01:49,949] Trial 47 finished with value: 0.8718861185506137 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.01102105505754124, 'subsample': 0.7392446659871328, 'colsample_bytree': 0.8667709616171205, 'min_child_weight': 9, 'gamma': 0.27138946446306833, 'reg_alpha': 0.021772851329855375, 'reg_lambda': 1.643817351230532, 'scale_pos_weight': 138}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528:  98%|█████████▊| 49/50 [00:30<00:00,  1.63it/s]

[I 2026-05-30 12:01:50,391] Trial 48 finished with value: 0.883458644432981 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.07151917555955796, 'subsample': 0.8687197153987936, 'colsample_bytree': 0.8869545569867682, 'min_child_weight': 2, 'gamma': 0.49977384506632433, 'reg_alpha': 0.05602580809707003, 'reg_lambda': 0.8994512908003356, 'scale_pos_weight': 112}. Best is trial 22 with value: 0.8645276267953204.

Best trial: 22. Best value: 0.864528: 100%|██████████| 50/50 [00:31<00:00,  1.58it/s]

[I 2026-05-30 12:01:51,160] Trial 49 finished with value: 0.88709677177869 and parameters: {'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.013086818309565425, 'subsample': 0.6944852977129128, 'colsample_bytree': 0.7399189890270064, 'min_child_weight': 8, 'gamma': 0.03309370077006531, 'reg_alpha': 0.026597966173418888, 'reg_lambda': 1.5882135762809497, 'scale_pos_weight': 146}. Best is trial 22 with value: 0.8645276267953204.
Best Hyperparameters :  {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.011884990791074808, 'subsample': 0.7114365643728696, 'colsample_bytree': 0.8558388814317627, 'min_child_weight': 10, 'gamma': 0.3151034296623495, 'reg_alpha': 0.022643887815158276, 'reg_lambda': 1.1655203960911897, 'scale_pos_weight': 123}
Fold 1 -  Recall: 0.9355, Precision: 0.6744
Fold 2 -  Recall: 0.9836, Precision: 0.6316
Fold 3 -  Recall: 0.9836, Precision: 0.6452
Fold 4 -  Recall: 1.0000, Precision: 0.6392
Fold 5 -  Recall: 0.9677, Precision: 0.5882
CV Average Recall: 0.9741 (+/- 0.0218)
CV Average Precision: 0.6357 (+/- 0.0278)

### Ensemble: LightGBM + Logistics Regression

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier, StackingClassifier

lgb_model = lgb.LGBMClassifier(
    is_unbalance=True,
    learning_rate=0.05,
    n_estimators=500,
    max_depth=5,
    num_leaves=31,
    random_state=42
)

lgb_model.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Training a simple logistic regression model for comparision (with SMOTE data)
log_reg_model = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
log_reg_model.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Soft voting ensemble of XGBoost, LightGBM and Logistic Regression
voting_clf = VotingClassifier(
    estimators=[
        ('xgb', xgb_final_classifier),
        ('lgb', lgb_model),
        ('log_reg', log_reg_model)
    ],
    voting='soft',
    weights=[1.5, 1.2, 0.8]
)

voting_clf.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)

# Stacking ensemble using the predictions of the base models which is used as the features
# for the meta model (Logistic Regression)

stacking_clf = StackingClassifier(
    estimators=[
        ('xgb', xgb_final_classifier),
        ('lgb', lgb_model)
    ],
    final_estimator=LogisticRegression(C=1.0),
    cv=5,
    stack_method='predict_proba'
)

stacking_clf.fit(X_train_hot_rolling_smote, y_train_hot_rolling_smote)


# Evaluating both the ensemble models on test set with threshold 0.5

for name, model in [('Voting', voting_clf), ('Stacking', stacking_clf)]:
    y_pred = model.predict(X_test_hot_rolling)
    print(f"\n{name} Ensemble Performance : ")
    print(f"Recall : {recall_score(y_test_hot_rolling, y_pred):.4f}")
    print(f"Precision : {precision_score(y_test_hot_rolling, y_pred):.4f}")

[LightGBM] [Info] Number of positive: 308, number of negative: 1028
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000321 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5099
[LightGBM] [Info] Number of data points in the train set: 1336, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.230539 -> initscore=-1.205271
[LightGBM] [Info] Start training from score -1.205271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

### Evaluation - Achieving 100% Recall and >90% Accuracy

In [23]:
def evaluate_model(model, X_test, y_test, threshold=0.5, model_name="Model"):
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    y_pred = (y_pred_proba >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    recall = tp / (tp + fn) if (tp+fn) > 0 else 0
    precision = tp / (tp + fp) if (tp+fp) > 0 else 0
    print(f"\n{model_name} - Threshold {threshold:.2f}")
    print(f"Confusion Matrix: TP={tp}, FP={fp}, FN={fn}, TN={tn}")
    print(f"Recall: {recall:.4f}  (Target: 1.0000)")
    print(f"Precision: {precision:.4f} (Target: >0.90)")
    return recall, precision, y_pred_proba


best_model = stacking_clf
evaluate_model(best_model, X_test_hot_rolling, y_test_hot_rolling, threshold=0.5)

Model - Threshold 0.50
Confusion Matrix: TP=4, FP=15, FN=9, TN=243
Recall: 0.3077  (Target: 1.0000)
Precision: 0.2105 (Target: >0.90)

(np.float64(0.3076923076923077),
 np.float64(0.21052631578947367),
 array([0.0113776 , 0.01204611, 0.01146145, 0.01150068, 0.01275571,
        0.16283433, 0.01130061, 0.01258737, 0.01140924, 0.01125489,
        0.83349654, 0.01209925, 0.01171033, 0.01197426, 0.01132013,
        0.0116562 , 0.01182085, 0.01187918, 0.01131281, 0.01236827,
        0.10613723, 0.87266362, 0.01281937, 0.01132131, 0.37063887,
        0.03810322, 0.79407844, 0.01124815, 0.09517967, 0.01799671,
        0.23092727, 0.01128761, 0.01141485, 0.01139375, 0.82496704,
        0.06385921, 0.01167279, 0.0119034 , 0.09074624, 0.01191553,
        0.01175271, 0.01151343, 0.01143428, 0.05936776, 0.04700313,
        0.01585226, 0.79824712, 0.011338  , 0.01128643, 0.03902182,
        0.01852345, 0.01335117, 0.06746929, 0.01172823, 0.01188326,
        0.01177865, 0.02477087, 0.01235482, 0.80843804, 0.02132491,
        0.41893997, 0.17825443, 0.01127996, 0.04435977, 0.01139956,
        0.01127825, 0.29083014, 0.01132773, 0.01228338, 0.01124372,
        0.10145817, 0.01157703, 0.01157155, 0.01150135, 0.01127546,
        0.01144977, 0.03315803, 0.07100244, 0.01124611, 0.01127827,
        0.01231936, 0.01382819, 0.0124714 , 0.02096817, 0.61295197,
        0.01274486, 0.05839928, 0.012192  , 0.01146489, 0.01235999,
        0.01150696, 0.01134194, 0.07609077, 0.01996858, 0.01237372,
        0.01143622, 0.06348123, 0.79653691, 0.08730062, 0.09555887,
        0.01371701, 0.05094311, 0.51846622, 0.01171463, 0.05358301,
        0.01123622, 0.01767171, 0.01193318, 0.74768436, 0.01206159,
        0.01149674, 0.03020596, 0.01134231, 0.01129283, 0.01127498,
        0.01719301, 0.0177406 , 0.01169127, 0.0124214 , 0.01246529,
        0.01193095, 0.01129254, 0.01124432, 0.01155293, 0.0125145 ,
        0.01361969, 0.84565012, 0.01204357, 0.16801958, 0.01569262,
        0.01193093, 0.01124452, 0.01550375, 0.89863168, 0.01262757,
        0.01147829, 0.01127046, 0.01128788, 0.01134159, 0.10498449,
        0.01131259, 0.01177054, 0.19180366, 0.01262045, 0.01128792,
        0.01129922, 0.01134008, 0.07868286, 0.02521984, 0.02192337,
        0.01385516, 0.73769498, 0.05530848, 0.01175077, 0.0120732 ,
        0.01580719, 0.01146656, 0.01140063, 0.01906323, 0.01305671,
        0.01277336, 0.14618709, 0.01601542, 0.01123695, 0.17617732,
        0.0113074 , 0.01161335, 0.01126839, 0.23309817, 0.01140289,
        0.01518933, 0.0114174 , 0.01170434, 0.01138222, 0.01126349,
        0.01175091, 0.01136106, 0.01231994, 0.66311944, 0.01169336,
        0.01167469, 0.0121034 , 0.01175159, 0.90013059, 0.01135196,
        0.16965704, 0.01244747, 0.01125314, 0.01138706, 0.0662256 ,
        0.01166007, 0.01139805, 0.19871739, 0.01132538, 0.02571102,
        0.01215903, 0.11564775, 0.01168891, 0.6889965 , 0.01173026,
        0.03310003, 0.02283321, 0.01130599, 0.01161393, 0.14436831,
        0.65849484, 0.011401  , 0.01129425, 0.01148923, 0.01131604,
        0.01131815, 0.01132701, 0.01129162, 0.01162535, 0.01134924,
        0.05981736, 0.01136561, 0.04014549, 0.27267179, 0.26758691,
        0.01129435, 0.01132564, 0.01136933, 0.0327229 , 0.01315906,
        0.01217556, 0.01130112, 0.37830012, 0.0178968 , 0.68149741,
        0.06675606, 0.01130879, 0.01130794, 0.01125062, 0.01142804,
        0.0113474 , 0.01148788, 0.01326761, 0.03077936, 0.0115541 ,
        0.01132347, 0.06768705, 0.01138621, 0.0142834 , 0.01196865,
        0.01151317, 0.01123682, 0.81983751, 0.01442073, 0.01196087,
        0.01246008, 0.02612122, 0.01127618, 0.01126354, 0.01125069,
        0.04240004, 0.01258808, 0.01123735, 0.01634756, 0.07125455,
        0.01145798, 0.01135545, 0.01136541, 0.01275129, 0.0227109 ,
        0.01132365, 0.01185257, 0.01363849, 0.31663853, 0.31769443,
        0.01168108]))

In [24]:
# Threshold tuning using Precision-Recall curve

from sklearn.model_selection import train_test_split

def find_optimal_threshold(model, X_val, y_val, target_recall=1.0, target_precision=0.9):
    y_proba = model.predict_proba(X_val)[:, 1]
    precisions, recalls, thresholds = precision_recall_curve(y_val, y_proba)
    # We need the highest threshold where recall >= target_recall and precision >= target_precision
    feasible = []
    for i in range(len(thresholds)):
        if recalls[i] >= target_recall - 1e-6 and precisions[i] >= target_precision - 1e-6:
            feasible.append((thresholds[i], recalls[i], precisions[i]))
    if feasible:
        # Among feasible, choose threshold that maximizes precision (or simply the one with highest precision)
        best = max(feasible, key=lambda x: x[2])   # highest precision
        return best[0], best[1], best[2]
    else:
        # No threshold satisfies both; find threshold that gives recall=1.0 with best precision
        recall_1_indices = [i for i, r in enumerate(recalls) if r >= target_recall - 1e-6]
        if recall_1_indices:
            best_idx = max(recall_1_indices, key=lambda i: precisions[i])
            return thresholds[best_idx], recalls[best_idx], precisions[best_idx]
        else:
            return 0.5, recalls[-1], precisions[-1]
        
        
X_train_final, X_val_thresh, y_train_final, y_val_thresh = train_test_split(
    X_train_hot_rolling_smote, 
    y_train_hot_rolling_smote, 
    test_size=0.2,
    stratify=y_train_hot_rolling_smote,
    random_state=42
)

# Retrain best model on X_train_final
final_model = stacking_clf 
final_model.fit(X_train_final, y_train_final)

opt_threshold, opt_recall, opt_precision = find_optimal_threshold(
    final_model, X_val_thresh, y_val_thresh, target_recall=1.0, target_precision=0.9
)
print(f"\nOptimal threshold: {opt_threshold:.3f} (Recall={opt_recall:.4f}, Precision={opt_precision:.4f})")


# Evaluate on test set with optimal threshold
_, _, y_proba_test = evaluate_model(final_model, X_test_hot_rolling, y_test_hot_rolling, threshold=opt_threshold, model_name="Final Model with Optimal Threshold")

[LightGBM] [Info] Number of positive: 246, number of negative: 822
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4929
[LightGBM] [Info] Number of data points in the train set: 1068, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.230337 -> initscore=-1.206409
[LightGBM] [Info] Start training from score -1.206409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [25]:

# Final Check: Guarantee Recall = 100% on test?

# If recall is still < 100%, we can try lowering threshold further until recall=1.0
def threshold_for_recall_1(model, X_val, y_val):
    y_proba = model.predict_proba(X_val)[:, 1]
    precisions, recalls, thresholds = precision_recall_curve(y_val, y_proba)
    for i in range(len(thresholds)):
        if recalls[i] >= 1.0 - 1e-6:
            return thresholds[i], precisions[i]
    return 0.1, precisions[-1]   # fallback

thresh_recall1, prec_at_thresh = threshold_for_recall_1(final_model, X_val_thresh, y_val_thresh)
print(f"\nThreshold for 100% recall: {thresh_recall1:.3f} (Precision = {prec_at_thresh:.4f})")

# Evaluate test set with that threshold
_, _, _ = evaluate_model(final_model, X_test_hot_rolling, y_test_hot_rolling, threshold=thresh_recall1, model_name="100% Recall Threshold")

Threshold for 100% recall: 0.010 (Precision = 0.2313)

100% Recall Threshold - Threshold 0.01
Confusion Matrix: TP=13, FP=258, FN=0, TN=0
Recall: 1.0000  (Target: 1.0000)
Precision: 0.0480 (Target: >0.90)